# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pow_ice_page_v3.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import datetime
import sqlite3


class Ui_page_v3(object):
    def __init__(self, productos_venta=None):
        self.productos_venta = productos_venta or []
        self.user_active = None
        self.total = None

    def setupUi(self, page_v3):
        self.page_v3 = page_v3  # Guardar referencia a la ventana principal
        page_v3.setObjectName("page_v3")
        page_v3.resize(1024, 600)
        page_v3.setWindowFlags(QtCore.Qt.Window | QtCore.Qt.CustomizeWindowHint | QtCore.Qt.WindowTitleHint)  # Disable close button
        
        self.user_active = QtWidgets.QLabel(page_v3)
        self.user_active.setGeometry(QtCore.QRect(150, 0, 300, 20))
        self.user_active.setObjectName("user_active")
        
        # Agregar label para fecha y hora
        self.datetime_label = QtWidgets.QLabel(page_v3)
        self.datetime_label.setGeometry(QtCore.QRect(150, 20, 300, 20))
        self.datetime_label.setObjectName("datetime_label")
        
        # Agregar label para el total con fuente más grande
        self.total_label = QtWidgets.QLabel(page_v3)
        self.total_label.setGeometry(QtCore.QRect(150, 40, 300, 40))  # Aumentado el alto para acomodar texto más grande
        self.total_label.setObjectName("total_label")
        font = QtGui.QFont()
        font.setPointSize(16)  # Tamaño de fuente más grande
        self.total_label.setFont(font)
        
        # Timer para actualizar la fecha y hora
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.update_datetime)
        self.timer.start(60000)  # Actualizar cada minuto (60000 ms)
        
        # Actualizar la fecha y hora inmediatamente
        current_datetime = datetime.now().strftime("%d/%m/%Y %H:%M")
        self.datetime_label.setText(f"Fecha y hora: {current_datetime}")
        
        self.label = QtWidgets.QLabel(page_v3)
        self.label.setGeometry(QtCore.QRect(160, 100, 111, 22))  # Movido más abajo
        self.label.setObjectName("label")
        
        self.radioButton = QtWidgets.QRadioButton(page_v3)
        self.radioButton.setGeometry(QtCore.QRect(160, 130, 114, 28))  # Movido más abajo
        self.radioButton.setObjectName("radioButton")
        self.radioButton.toggled.connect(self.on_efectivo_toggled)  # Conectar el evento de cambio
        
        self.radioButton_2 = QtWidgets.QRadioButton(page_v3)
        self.radioButton_2.setGeometry(QtCore.QRect(160, 160, 114, 28))  # Movido más abajo
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_2.toggled.connect(self.on_daviplata_toggled)  # Conectar el evento de cambio
        
        self.radioButton_3 = QtWidgets.QRadioButton(page_v3)
        self.radioButton_3.setGeometry(QtCore.QRect(160, 190, 114, 28))  # Movido más abajo
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_3.toggled.connect(self.on_pago_mixto_toggled)  # Conectar el evento de cambio
        
        self.radioButton_4 = QtWidgets.QRadioButton(page_v3)
        self.radioButton_4.setGeometry(QtCore.QRect(160, 220, 114, 28))  # Movido más abajo
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_4.toggled.connect(self.on_nequi_toggled)  # Conectar el evento de cambio
        
        # Label para "Recibido" (inicialmente oculto)
        self.recibido_label = QtWidgets.QLabel(page_v3)
        self.recibido_label.setGeometry(QtCore.QRect(400, 130, 111, 22))
        self.recibido_label.setObjectName("recibido_label")
        self.recibido_label.hide()
        
        # Campo de texto para el valor recibido (inicialmente oculto)
        self.recibido_input = QtWidgets.QLineEdit(page_v3)
        self.recibido_input.setGeometry(QtCore.QRect(400, 160, 111, 22))
        self.recibido_input.setObjectName("recibido_input")
        self.recibido_input.setValidator(QtGui.QIntValidator())  # Solo permite números enteros
        self.recibido_input.hide()
        
        # Radio buttons para pago mixto (inicialmente ocultos)
        self.radioButton_mixto_nequi = QtWidgets.QRadioButton(page_v3)
        self.radioButton_mixto_nequi.setGeometry(QtCore.QRect(400, 130, 114, 28))
        self.radioButton_mixto_nequi.setObjectName("radioButton_mixto_nequi")
        self.radioButton_mixto_nequi.hide()
        
        self.radioButton_mixto_daviplata = QtWidgets.QRadioButton(page_v3)
        self.radioButton_mixto_daviplata.setGeometry(QtCore.QRect(400, 160, 114, 28))
        self.radioButton_mixto_daviplata.setObjectName("radioButton_mixto_daviplata")
        self.radioButton_mixto_daviplata.hide()
        
        # Crear un grupo de botones para los radio buttons de pago mixto
        self.mixto_button_group = QtWidgets.QButtonGroup(page_v3)
        self.mixto_button_group.addButton(self.radioButton_mixto_nequi)
        self.mixto_button_group.addButton(self.radioButton_mixto_daviplata)
        
        # Label para efectivo en pago mixto (inicialmente oculto)
        self.efectivo_mixto_label = QtWidgets.QLabel(page_v3)
        self.efectivo_mixto_label.setGeometry(QtCore.QRect(400, 190, 111, 22))
        self.efectivo_mixto_label.setObjectName("efectivo_mixto_label")
        self.efectivo_mixto_label.hide()
        
        # Campo de texto para efectivo en pago mixto (inicialmente oculto)
        self.efectivo_mixto_input = QtWidgets.QLineEdit(page_v3)
        self.efectivo_mixto_input.setGeometry(QtCore.QRect(400, 220, 111, 22))
        self.efectivo_mixto_input.setObjectName("efectivo_mixto_input")
        self.efectivo_mixto_input.setValidator(QtGui.QIntValidator())  # Solo permite números enteros
        self.efectivo_mixto_input.hide()
        self.efectivo_mixto_input.textChanged.connect(lambda: self.update_difference(self.efectivo_mixto_input, self.transferencia_mixto_input))

        # Label para transferencia en pago mixto (inicialmente oculto)
        self.transferencia_mixto_label = QtWidgets.QLabel(page_v3)
        self.transferencia_mixto_label.setGeometry(QtCore.QRect(520, 190, 111, 22))
        self.transferencia_mixto_label.setObjectName("transferencia_mixto_label")
        self.transferencia_mixto_label.hide()
        
        # Campo de texto para transferencia en pago mixto (inicialmente oculto)
        self.transferencia_mixto_input = QtWidgets.QLineEdit(page_v3)
        self.transferencia_mixto_input.setGeometry(QtCore.QRect(520, 220, 111, 22))
        self.transferencia_mixto_input.setObjectName("transferencia_mixto_input")
        self.transferencia_mixto_input.setValidator(QtGui.QIntValidator())  # Solo permite números enteros
        self.transferencia_mixto_input.hide()
        self.transferencia_mixto_input.textChanged.connect(lambda: self.update_difference(self.transferencia_mixto_input, self.efectivo_mixto_input))

        # Labels para mostrar las diferencias (inicialmente ocultos)
        self.diferencia_efectivo_label = QtWidgets.QLabel(page_v3)
        self.diferencia_efectivo_label.setGeometry(QtCore.QRect(400, 250, 111, 22))
        self.diferencia_efectivo_label.setObjectName("diferencia_efectivo_label")
        self.diferencia_efectivo_label.hide()

        self.diferencia_transferencia_label = QtWidgets.QLabel(page_v3)
        self.diferencia_transferencia_label.setGeometry(QtCore.QRect(520, 250, 111, 22))
        self.diferencia_transferencia_label.setObjectName("diferencia_transferencia_label")
        self.diferencia_transferencia_label.hide()
        
        self.pushButton = QtWidgets.QPushButton(page_v3)
        self.pushButton.setGeometry(QtCore.QRect(310, 270, 91, 30))  # Movido más abajo
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.on_ok_clicked)  # Conectar el evento de clic
        
        self.pushButton_2 = QtWidgets.QPushButton(page_v3)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 270, 91, 30))  # Movido más abajo
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.go_back)

        self.retranslateUi(page_v3)
        QtCore.QMetaObject.connectSlotsByName(page_v3)

    def go_back(self):
        try:
            # Simplemente cerrar la ventana actual
            self.page_v3.close()
        except Exception as e:
            print(f"Error al cerrar la ventana: {e}")

    def set_user_active(self, user_name):
        """Update the user_active label with the given username"""
        self.user_active.setText(f"usuario activo: {user_name}")

    def update_datetime(self):
        """Actualiza la fecha y hora en el label"""
        try:
            current_datetime = datetime.now().strftime("%d/%m/%Y %H:%M")
            self.datetime_label.setText(f"Fecha y hora: {current_datetime}")
        except Exception as e:
            print(f"Error al actualizar la fecha y hora: {e}")
            self.datetime_label.setText("Fecha y hora: --/--/---- --:--")

    def set_total(self, total):
        """Actualiza el label del total"""
        self.total_label.setText(f"Total: ${total}")

    def clear_right_side(self):
        """Limpia todos los elementos del lado derecho"""
        self.recibido_label.hide()
        self.recibido_input.hide()
        self.recibido_input.clear()
        self.radioButton_mixto_nequi.hide()
        self.radioButton_mixto_daviplata.hide()
        self.efectivo_mixto_label.hide()
        self.efectivo_mixto_input.hide()
        self.efectivo_mixto_input.clear()
        self.transferencia_mixto_label.hide()
        self.transferencia_mixto_input.hide()
        self.transferencia_mixto_input.clear()
        self.diferencia_efectivo_label.hide()
        self.diferencia_transferencia_label.hide()

    def on_efectivo_toggled(self, checked):
        """Maneja el evento cuando se selecciona/deselecciona el radio button de efectivo"""
        self.clear_right_side()  # Limpiar todo primero
        if checked:
            self.recibido_label.show()
            self.recibido_input.show()

    def on_daviplata_toggled(self, checked):
        """Maneja el evento cuando se selecciona/deselecciona el radio button de daviplata"""
        self.clear_right_side()  # Limpiar todo primero

    def on_pago_mixto_toggled(self, checked):
        """Maneja el evento cuando se selecciona/deselecciona el radio button de pago mixto"""
        self.clear_right_side()  # Limpiar todo primero
        if checked:
            self.radioButton_mixto_nequi.show()
            self.radioButton_mixto_daviplata.show()
            self.efectivo_mixto_label.show()
            self.efectivo_mixto_input.show()
            self.transferencia_mixto_label.show()
            self.transferencia_mixto_input.show()
            self.diferencia_efectivo_label.show()
            self.diferencia_transferencia_label.show()

    def on_nequi_toggled(self, checked):
        """Maneja el evento cuando se selecciona/deselecciona el radio button de nequi"""
        self.clear_right_side()  # Limpiar todo primero

    def on_ok_clicked(self):
        try:
            # Verificar si se ha seleccionado algún método de pago
            if not (self.radioButton.isChecked() or self.radioButton_2.isChecked() or 
                   self.radioButton_3.isChecked() or self.radioButton_4.isChecked()):
                QtWidgets.QMessageBox.warning(self.page_v3, "Advertencia", 
                    "Por favor seleccione un método de pago")
                return
            
            # Obtener el tipo de pago seleccionado y la diferencia
            diferencia = None  # Por defecto, la diferencia es NULL
            if self.radioButton.isChecked():
                tipo_pago = "efectivo"
            elif self.radioButton_2.isChecked():
                tipo_pago = "daviplata"
            elif self.radioButton_3.isChecked():
                tipo_pago = "pago mixto"
                # Solo para pago mixto, obtener la diferencia del total
                diferencia = float(self.total_label.text().replace("Total: $", "").replace(",", ""))
            elif self.radioButton_4.isChecked():
                tipo_pago = "nequi"
            
            # Obtener el usuario activo
            current_user = self.user_active.text().replace("usuario activo: ", "")
            
            # Obtener fecha y hora actual
            fecha = datetime.now().strftime("%Y-%m-%d")
            hora = datetime.now().strftime("%H:%M:%S")
            
            # Conectar a la base de datos
            conn = sqlite3.connect('/home/andres/Documentos/app_heladeria/databases/Pow_Ice')
            cursor = conn.cursor()
            
            # Obtener id_usuario
            cursor.execute("SELECT id FROM usuarios WHERE nombre = ?", (current_user,))
            user_result = cursor.fetchone()
            if not user_result:
                print(f"Usuario '{current_user}' no encontrado en la base de datos.")
                return
            id_usuario = user_result[0]
            
            # Obtener id_tipo
            cursor.execute("SELECT id FROM tipo_de_pago WHERE tipo = ?", (tipo_pago,))
            tipo_result = cursor.fetchone()
            if not tipo_result:
                print(f"Tipo de pago '{tipo_pago}' no encontrado en la base de datos.")
                return
            id_tipo = tipo_result[0]
            
            # Insertar en la tabla ventas usando los datos recibidos
            insertados = 0
            for producto, cantidad in self.productos_venta:
                print(f"Intentando insertar producto: {producto}, cantidad: {cantidad}")
                
                # Obtener id_product
                cursor.execute("SELECT id FROM products WHERE product = ?", (producto,))
                prod_result = cursor.fetchone()
                if not prod_result:
                    print(f"Producto '{producto}' no encontrado en la base de datos.")
                    continue
                id_product = prod_result[0]

                # Insertar en la tabla ventas
                try:
                    cursor.execute(
                        """INSERT INTO ventas (fecha, id_usuario, id_product, hora, id_tipo, diferencia, cant)
                        VALUES (?, ?, ?, ?, ?, ?, ?)""",
                        (fecha, id_usuario, id_product, hora, id_tipo, diferencia, cantidad)
                    )
                    print(f"Insertado: {producto} x{cantidad}")
                    insertados += 1
                except Exception as e:
                    print(f"Error al insertar venta: {e}")

            print(f"Total de productos insertados en ventas: {insertados}")
            
            # Guardar cambios y cerrar conexión
            conn.commit()
            conn.close()
            
            # Cerrar la ventana actual
            self.page_v3.close()
            
        except Exception as e:
            print(f"Error al guardar la venta: {e}")
            if 'conn' in locals():
                conn.close()

    def update_difference(self, source_input, target_input):
        """Actualiza el campo de texto objetivo con la diferencia"""
        try:
            total = int(self.total_label.text().replace("Total: $", ""))
            source_text = source_input.text()
            
            if source_text:
                source_value = int(source_text)
                if source_value <= total:
                    difference = total - source_value
                    target_input.setText(str(difference))
                else:
                    target_input.setText("0")
            else:
                target_input.setText("0")
                
        except ValueError:
            target_input.setText("0")

    def retranslateUi(self, page_v3):
        _translate = QtCore.QCoreApplication.translate
        page_v3.setWindowTitle(_translate("page_v3", "page_v3"))
        self.user_active.setText(_translate("page_v3", "usuario activo: _____"))
        current_datetime = datetime.now().strftime("%d/%m/%Y %H:%M")
        self.datetime_label.setText(f"Fecha y hora: {current_datetime}")
        self.total_label.setText(_translate("page_v3", "Total: $0"))
        self.label.setText(_translate("page_v3", "Medio De Pago"))
        self.radioButton.setText(_translate("page_v3", "Efectivo"))
        self.radioButton_2.setText(_translate("page_v3", "Daviplata"))
        self.radioButton_3.setText(_translate("page_v3", "Pago Mixto"))
        self.radioButton_4.setText(_translate("page_v3", "Nequi"))
        self.pushButton_2.setText(_translate("page_v3", "Atrás"))
        self.pushButton.setText(_translate("page_v3", "OK"))
        self.recibido_label.setText(_translate("page_v3", "Recibido:"))
        self.radioButton_mixto_nequi.setText(_translate("page_v3", "Nequi"))
        self.radioButton_mixto_daviplata.setText(_translate("page_v3", "Daviplata"))
        self.efectivo_mixto_label.setText(_translate("page_v3", "Efectivo:"))
        self.transferencia_mixto_label.setText(_translate("page_v3", "Transferencia:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    page_v3 = QtWidgets.QDialog()
    ui = Ui_page_v3()
    ui.setupUi(page_v3)
    page_v3.show()
    sys.exit(app.exec_())
