# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pow_ice_page_v1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3  # Import SQLite for database interaction
from window.ventana_v2 import Ui_page_v2  # Import ventana_v2
from datetime import datetime  # Import datetime para manejar fechas


class Ui_page_v1(object):
    def setupUi(self, page_v1):
        self.page_v1 = page_v1  # Guardar referencia a la ventana
        page_v1.setObjectName("page_v1")
        page_v1.resize(1024, 600)
        page_v1.setWindowFlags(QtCore.Qt.Window | QtCore.Qt.CustomizeWindowHint | QtCore.Qt.WindowTitleHint)  # Disable close button
        page_v1.setWindowTitle("Pedido 1")  # Establecer título de la ventana principal

        # Crear frame de fondo
        self.background_frame = QtWidgets.QFrame(page_v1)
        self.background_frame.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.background_frame.setStyleSheet("background-color: #E6F3FF;")  # Mismo color que el fondo
        self.background_frame.lower()  # Enviar al fondo

        # Establecer el color de fondo de la ventana (tono azul claro)
        page_v1.setStyleSheet("""
            QWidget {
                background-color: #E6F3FF;  /* Azul pastel claro */
            }
            QPushButton {
                background-color: #4A90E2;  /* Azul medio */
                border: 3px solid #2C5282;  /* Azul oscuro */
                border-radius: 15px;
                color: white;  /* Texto blanco para mejor contraste */
                padding: 5px;
                font-size: 32px;
            }
            QPushButton:hover {
                background-color: #2C5282;  /* Azul oscuro al pasar el mouse */
                color: white;
            }
            QLabel {
                color: #1A365D;  /* Azul muy oscuro para el texto */
                font-size: 32px;
            }
            QTableWidget {
                background-color: white;
                border: 3px solid #4A90E2;
                border-radius: 10px;
                gridline-color: #E6F3FF;
            }
            QTableWidget::item {
                padding: 5px;
            }
            QTableWidget::item:selected {
                background-color: #4A90E2;
                color: white;
            }
            QHeaderView::section {
                background-color: #4A90E2;
                color: white;
                padding: 5px;
                border: 1px solid #2C5282;
            }
            QLineEdit {
                background-color: white;
                border: 2px solid #4A90E2;
                border-radius: 10px;
                padding: 5px;
                color: #1A365D;
                font-size: 32px;
            }
            QLineEdit:focus {
                border: 2px solid #2C5282;
                background-color: #F0F7FF;
            }
            QRadioButton {
                color: #1A365D;
                font-size: 32px;
            }
            QRadioButton::indicator {
                width: 20px;
                height: 20px;
            }
            QRadioButton::indicator:unchecked {
                border: 2px solid #4A90E2;
                background-color: white;
                border-radius: 10px;
            }
            QRadioButton::indicator:checked {
                border: 2px solid #2C5282;
                background-color: #4A90E2;
                border-radius: 10px;
            }
        """)

        # Crear layout vertical principal
        main_layout = QtWidgets.QVBoxLayout(page_v1)
        main_layout.setContentsMargins(40, 40, 40, 40)  # Aumentado los márgenes
        main_layout.setSpacing(30)  # Aumentado el espaciado

        # Configurar fuente base
        base_font = QtGui.QFont()
        base_font.setPointSize(14)  # Tamaño de fuente base

        # Título
        self.title_label = QtWidgets.QLabel(page_v1)
        self.title_label.setObjectName("title_label")
        self.title_label.setGeometry(QtCore.QRect(0, 50, 800, 60))
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        title_font = QtGui.QFont()
        title_font.setPointSize(32)
        title_font.setBold(True)
        self.title_label.setFont(title_font)
        self.title_label.setText("Pow Ice")
        self.title_label.setStyleSheet("""
            QLabel {
                color: #1A365D;  /* Azul muy oscuro para el título */
                font-weight: bold;
                background-color: transparent;
            }
        """)
        main_layout.addWidget(self.title_label)

        # LineEdit para el usuario
        self.username_in = QtWidgets.QLineEdit(page_v1)
        self.username_in.setObjectName("username_in")
        self.username_in.setFixedWidth(400)  # Aumentado el ancho
        self.username_in.setFixedHeight(50)  # Aumentado el alto
        self.username_in.setAlignment(QtCore.Qt.AlignCenter)
        self.username_in.setFont(base_font)
        main_layout.addWidget(self.username_in, alignment=QtCore.Qt.AlignCenter)

        # Label para mensajes de validación
        self.user_ivalid = QtWidgets.QLabel(page_v1)
        self.user_ivalid.setObjectName("user_ivalid")
        self.user_ivalid.setAlignment(QtCore.Qt.AlignCenter)
        self.user_ivalid.setFont(base_font)
        main_layout.addWidget(self.user_ivalid)

        # Layout horizontal para los botones OK y Atrás
        button_container = QtWidgets.QWidget()
        button_container.setFixedWidth(410)  # Ancho fijo para contener ambos botones
        button_layout = QtWidgets.QHBoxLayout(button_container)
        button_layout.setSpacing(0)
        button_layout.setContentsMargins(0, 0, 0, 0)

        # Botón OK
        self.pushButton = QtWidgets.QPushButton(page_v1)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setFixedWidth(200)  # Aumentado el ancho
        self.pushButton.setFixedHeight(50)  # Aumentado el alto
        self.pushButton.setFont(base_font)
        self.pushButton.clicked.connect(self.validate_user)
        button_layout.addWidget(self.pushButton)

        # Botón Atrás
        self.pushButton_2 = QtWidgets.QPushButton(page_v1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setFixedWidth(200)  # Aumentado el ancho
        self.pushButton_2.setFixedHeight(50)  # Aumentado el alto
        self.pushButton_2.setFont(base_font)
        self.pushButton_2.clicked.connect(self.go_back)
        button_layout.addWidget(self.pushButton_2)

        # Agregar el contenedor de botones al layout principal
        main_layout.addWidget(button_container, alignment=QtCore.Qt.AlignCenter)

        # Botón Venta del día
        self.venta_dia_button = QtWidgets.QPushButton(page_v1)
        self.venta_dia_button.setObjectName("venta_dia_button")
        self.venta_dia_button.setFixedWidth(400)  # Aumentado el ancho
        self.venta_dia_button.setFixedHeight(50)  # Aumentado el alto
        self.venta_dia_button.setFont(base_font)
        self.venta_dia_button.clicked.connect(self.show_ventas_dia)
        main_layout.addWidget(self.venta_dia_button, alignment=QtCore.Qt.AlignCenter)

        # Agregar espaciador flexible al final
        main_layout.addStretch()

        self.user_name = None  # Store the user's name

        self.retranslateUi(page_v1)
        QtCore.QMetaObject.connectSlotsByName(page_v1)

    def go_back(self):
        try:
            # Obtener la ventana principal
            main_window = None
            for widget in QtWidgets.QApplication.topLevelWidgets():
                if isinstance(widget, QtWidgets.QMainWindow):
                    main_window = widget
                    break
            
            if main_window:
                main_window.show()
                self.page_v1.close()
            else:
                print("No se encontró la ventana principal")
        except Exception as e:
            print(f"Error al volver a la ventana principal: {e}")

    def validate_user(self):
        input_text = self.username_in.text()
        if not input_text.isdigit():  # Check if input is numeric
            self.user_ivalid.setText("Usuario incorrecto")
            return

        user_id = int(input_text)
        try:
            # Connect to the database
            connection = sqlite3.connect('/home/andres/Documentos/databases_heladeria/Pow_Ice')
            cursor = connection.cursor()

            # Query to check if the ID exists and fetch the name
            cursor.execute("SELECT nombre FROM usuarios WHERE id = ?", (user_id,))
            result = cursor.fetchone()

            if result:
                self.user_name = result[0]  # Store the user's name
                self.user_ivalid.setText("Usuario correcto")
                self.open_ventana_v2()  # Open ventana_v2 if user is valid
            else:
                self.user_ivalid.setText("Usuario incorrecto")

        except sqlite3.Error as e:
            self.user_ivalid.setText("Error de BD")
            print(f"Database error: {e}")
        finally:
            if connection:
                connection.close()

    def open_ventana_v2(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_page_v2()
        self.ui.setupUi(self.window)
        self.ui.set_user_active(self.user_name)  # Pass the user's name to ventana_v2
        self.window.resize(1024, 600)  # Set resolution to 1024x600
        self.window.show()
        QtWidgets.QApplication.instance().activeWindow().hide()  # Hide the current window

    def show_ventas_dia(self):
        try:
            # Crear ventana de diálogo
            dialog = QtWidgets.QDialog(self.page_v1)
            dialog.setWindowTitle("Ventas del Día")
            dialog.resize(1000, 600)  # Aumentado el tamaño de la ventana

            # Crear layout vertical para la ventana
            layout = QtWidgets.QVBoxLayout(dialog)
            layout.setContentsMargins(40, 40, 40, 40)  # Aumentado los márgenes
            layout.setSpacing(20)  # Aumentado el espaciado

            # Configurar fuente para la tabla (más grande)
            table_font = QtGui.QFont()
            table_font.setPointSize(18)  # <-- Disminuir tamaño de fuente de la tabla a 18

            # Crear tabla
            table = QtWidgets.QTableWidget()
            table.setColumnCount(4)
            table.setHorizontalHeaderLabels(["Producto", "Cantidad", "Precio Unitario", "Total"])
            table.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
            table.setFont(table_font)
            table.verticalHeader().setDefaultSectionSize(50)  # Aumentado el alto de las filas

            # Conectar a la base de datos
            conn = sqlite3.connect('/home/andres/Documentos/databases_heladeria/Pow_Ice')
            cursor = conn.cursor()

            # Obtener la fecha actual
            fecha_actual = datetime.now().strftime('%Y-%m-%d')

            # Consultar ventas del día
            cursor.execute("""
                SELECT p.product, SUM(v.cant) as cantidad, p.price, SUM(v.cant * p.price) as total
                FROM ventas v
                JOIN products p ON v.id_product = p.id
                WHERE date(v.fecha) = ?
                GROUP BY p.id, p.product, p.price
                ORDER BY p.product
            """, (fecha_actual,))

            # Llenar la tabla con los resultados
            for row, data in enumerate(cursor.fetchall()):
                table.insertRow(row)
                for col, value in enumerate(data):
                    item = QtWidgets.QTableWidgetItem(str(value))
                    if col in [1, 2, 3]:  # Alinear números a la derecha
                        item.setTextAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)
                    item.setFont(table_font)  # <-- Aplica la fuente grande a cada celda
                    table.setItem(row, col, item)

            # Calcular total del día
            cursor.execute("""
                SELECT SUM(v.cant * p.price) as total_dia
                FROM ventas v
                JOIN products p ON v.id_product = p.id
                WHERE date(v.fecha) = ?
            """, (fecha_actual,))
            total_dia = cursor.fetchone()[0] or 0

            # Agregar la tabla al layout
            layout.addWidget(table)

            # Agregar label con el total
            total_label = QtWidgets.QLabel(f"Total del día: ${total_dia:,.0f}")
            total_label.setAlignment(QtCore.Qt.AlignRight)
            total_label.setFont(table_font)
            layout.addWidget(total_label)

            # Botón para cerrar
            close_button = QtWidgets.QPushButton("Cerrar")
            close_button.setFixedWidth(200)  # Aumentado el ancho
            close_button.setFixedHeight(50)  # Aumentado el alto
            close_button.setFont(table_font)
            close_button.clicked.connect(dialog.close)
            layout.addWidget(close_button, alignment=QtCore.Qt.AlignCenter)

            conn.close()
            dialog.exec_()

        except sqlite3.Error as e:
            QtWidgets.QMessageBox.critical(self.page_v1, "Error", f"Error de base de datos: {str(e)}")
        except Exception as e:
            QtWidgets.QMessageBox.critical(self.page_v1, "Error", f"Error inesperado: {str(e)}")

    def retranslateUi(self, page_v1):
        _translate = QtCore.QCoreApplication.translate
        page_v1.setWindowTitle(_translate("page_v1", "page_v1"))
        self.pushButton_2.setText(_translate("page_v1", "Atrás"))
        self.pushButton.setText(_translate("page_v1", "OK"))
        self.venta_dia_button.setText(_translate("page_v1", "Venta del día"))
