# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_vfinal.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import datetime


class Ui_page_vfinal(object):
    def setupUi(self, page_vfinal):
        self.page_vfinal = page_vfinal  # Guardar referencia a la ventana principal
        page_vfinal.setObjectName("page_vfinal")
        page_vfinal.resize(1024, 600)
        page_vfinal.setWindowFlags(QtCore.Qt.Window | QtCore.Qt.CustomizeWindowHint | QtCore.Qt.WindowTitleHint)  # Disable close button
        
        # Label para usuario activo
        self.user_active = QtWidgets.QLabel(page_vfinal)
        self.user_active.setGeometry(QtCore.QRect(150, 0, 300, 20))
        self.user_active.setObjectName("user_active")
        
        # Label para fecha y hora
        self.datetime_label = QtWidgets.QLabel(page_vfinal)
        self.datetime_label.setGeometry(QtCore.QRect(150, 20, 300, 20))
        self.datetime_label.setObjectName("datetime_label")
        
        # Label para el total
        self.total_label = QtWidgets.QLabel(page_vfinal)
        self.total_label.setGeometry(QtCore.QRect(150, 40, 300, 40))
        self.total_label.setObjectName("total_label")
        font = QtGui.QFont()
        font.setPointSize(10)  # Tamaño de fuente más grande
        self.total_label.setFont(font)
        
        # Label para el cambio
        self.change_label = QtWidgets.QLabel(page_vfinal)
        self.change_label.setGeometry(QtCore.QRect(150, 80, 300, 40))
        self.change_label.setObjectName("change_label")
        font = QtGui.QFont()
        font.setPointSize(16)  # Tamaño de fuente más grande
        self.change_label.setFont(font)
        
        # Label para método de pago
        self.payment_method_label = QtWidgets.QLabel(page_vfinal)
        self.payment_method_label.setGeometry(QtCore.QRect(150, 120, 700, 40))  # Aumentado el ancho para mostrar más texto
        self.payment_method_label.setObjectName("payment_method_label")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.payment_method_label.setFont(font)
        self.payment_method_label.setWordWrap(True)  # Permite que el texto se envuelva si es muy largo
        self.payment_method_label.setAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)  # Alineación a la izquierda y arriba
        
        # Botón OK para cerrar la ventana
        self.ok_button = QtWidgets.QPushButton(page_vfinal)
        self.ok_button.setGeometry(QtCore.QRect(400, 180, 91, 30))
        self.ok_button.setObjectName("ok_button")
        self.ok_button.clicked.connect(self.close_window)
        
        # Timer para actualizar la fecha y hora
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.update_datetime)
        self.timer.start(60000)  # Actualizar cada minuto (60000 ms)
        
        # Actualizar la fecha y hora inmediatamente
        current_datetime = datetime.now().strftime("%d/%m/%Y %H:%M")
        self.datetime_label.setText(f"Fecha y hora: {current_datetime}")
        
        self.retranslateUi(page_vfinal)
        QtCore.QMetaObject.connectSlotsByName(page_vfinal)

    def set_user_active(self, user_name):
        """Update the user_active label with the given username"""
        self.user_active.setText(f"usuario activo: {user_name}")

    def set_total(self, total, received=None):
        """Actualiza el label del total y calcula el cambio si se proporciona el monto recibido"""
        self.total_label.setText(f"Total: ${total}")
        
        if received is not None:
            try:
                # Convertir los valores a enteros
                total_value = int(total.replace('$', '').strip())
                received_value = int(received)
                
                # Calcular el cambio
                change = received_value - total_value
                
                # Mostrar el cambio
                self.change_label.setText(f"Cambio: ${change}")
            except ValueError:
                self.change_label.setText("Cambio: Error en el cálculo")
        else:
            self.change_label.setText("Cambio: $0")

    def set_payment_method(self, payment_method):
        """Actualiza el label del método de pago"""
        self.payment_method_label.setText(f"Método de pago: {payment_method}")

    def update_datetime(self):
        """Actualiza la fecha y hora en el label"""
        try:
            current_datetime = datetime.now().strftime("%d/%m/%Y %H:%M")
            self.datetime_label.setText(f"Fecha y hora: {current_datetime}")
        except Exception as e:
            print(f"Error al actualizar la fecha y hora: {e}")
            self.datetime_label.setText("Fecha y hora: --/--/---- --:--")

    def close_window(self):
        """Abre la ventana v2 y cierra la actual"""
        try:
            # Importar aquí para evitar la importación circular
            from window.ventana_v2 import Ui_page_v2
            
            # Crear nueva ventana v2
            self.window_v2 = QtWidgets.QWidget()
            self.ui_v2 = Ui_page_v2()
            self.ui_v2.setupUi(self.window_v2)
            
            # Obtener el usuario activo actual y pasarlo a v2
            current_user = self.user_active.text().replace("usuario activo: ", "")
            self.ui_v2.set_user_active(current_user)
            
            # Mostrar la ventana v2
            self.window_v2.resize(1024, 600)
            self.window_v2.show()
            
            # Cerrar la ventana actual
            self.page_vfinal.close()
            
        except Exception as e:
            print(f"Error al abrir ventana v2: {e}")

    def retranslateUi(self, page_vfinal):
        _translate = QtCore.QCoreApplication.translate
        page_vfinal.setWindowTitle(_translate("page_vfinal", "page_vfinal"))
        self.user_active.setText(_translate("page_vfinal", "usuario activo: _____"))
        current_datetime = datetime.now().strftime("%d/%m/%Y %H:%M")
        self.datetime_label.setText(f"Fecha y hora: {current_datetime}")
        self.total_label.setText(_translate("page_vfinal", "Total: $0"))
        self.change_label.setText(_translate("page_vfinal", "Cambio: $0"))
        self.payment_method_label.setText(_translate("page_vfinal", "Método de pago: "))
        self.ok_button.setText(_translate("page_vfinal", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    page_vfinal = QtWidgets.QDialog()
    ui = Ui_page_vfinal()
    ui.setupUi(page_vfinal)
    page_vfinal.show()
    sys.exit(app.exec_())
