# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pow_ice_page_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_page_v2(object):
    def setupUi(self, page_v2):
        self.page_v2 = page_v2  # Guardar referencia a la ventana principal
        page_v2.setObjectName("page_v2")
        page_v2.resize(1024, 600)
        page_v2.setWindowFlags(QtCore.Qt.Window | QtCore.Qt.CustomizeWindowHint | QtCore.Qt.WindowTitleHint)  # Disable close button
        self.user_active = QtWidgets.QLabel(page_v2)
        self.user_active.setGeometry(QtCore.QRect(150, 0, 300, 20))
        self.user_active.setObjectName("user_active")
        self.tableView = QtWidgets.QTableView(page_v2)
        self.tableView.setGeometry(QtCore.QRect(20, 40, 121, 211))
        self.tableView.setObjectName("tableView")

        # Botones principales (columna izquierda)
        self.Helados = QtWidgets.QPushButton(page_v2)
        self.Helados.setGeometry(QtCore.QRect(160, 30, 120, 30))  # Aumentado a 120 de ancho
        self.Helados.setObjectName("Helados")
        self.Helados.clicked.connect(self.show_cono1)

        self.Paletas = QtWidgets.QPushButton(page_v2)
        self.Paletas.setGeometry(QtCore.QRect(160, 60, 120, 30))  # Aumentado a 120 de ancho
        self.Paletas.setObjectName("Paletas")
        self.Paletas.clicked.connect(self.show_refrescante)

        self.Obleas = QtWidgets.QPushButton(page_v2)
        self.Obleas.setGeometry(QtCore.QRect(160, 90, 120, 30))  # Aumentado a 120 de ancho
        self.Obleas.setObjectName("Obleas")
        self.Obleas.clicked.connect(self.show_obleas)

        self.Brownie = QtWidgets.QPushButton(page_v2)
        self.Brownie.setGeometry(QtCore.QRect(160, 120, 120, 30))  # Aumentado a 120 de ancho
        self.Brownie.setObjectName("Brownie")
        self.Brownie.clicked.connect(self.show_brownie)

        self.Fresas = QtWidgets.QPushButton(page_v2)
        self.Fresas.setGeometry(QtCore.QRect(160, 150, 120, 30))  # Aumentado a 120 de ancho
        self.Fresas.setObjectName("Fresas")
        self.Fresas.clicked.connect(self.show_fresas)

        self.Waffles = QtWidgets.QPushButton(page_v2)
        self.Waffles.setGeometry(QtCore.QRect(160, 180, 120, 30))  # Aumentado a 120 de ancho
        self.Waffles.setObjectName("Waffles")
        self.Waffles.clicked.connect(self.show_waffles)

        self.Bebidas = QtWidgets.QPushButton(page_v2)
        self.Bebidas.setGeometry(QtCore.QRect(160, 210, 120, 30))  # Aumentado a 120 de ancho
        self.Bebidas.setObjectName("Bebidas")
        self.Bebidas.clicked.connect(self.show_bebidas)

        self.Otros = QtWidgets.QPushButton(page_v2)
        self.Otros.setGeometry(QtCore.QRect(160, 240, 120, 30))  # Aumentado a 120 de ancho
        self.Otros.setObjectName("Otros")

        # Botones de Helados (segunda columna)
        self.Cono1 = QtWidgets.QPushButton(page_v2)
        self.Cono1.setGeometry(QtCore.QRect(290, 30, 140, 30))  # Aumentado a 140 de ancho
        self.Cono1.setObjectName("Cono1")
        self.Cono1.hide()
        self.Cono1.clicked.connect(self.add_cono1)

        self.Cono2 = QtWidgets.QPushButton(page_v2)
        self.Cono2.setGeometry(QtCore.QRect(290, 70, 140, 30))  # Aumentado a 140 de ancho
        self.Cono2.setObjectName("Cono2")
        self.Cono2.hide()
        self.Cono2.clicked.connect(self.add_cono2)

        # Botones de Canasta (tercera columna)
        self.Canasta2 = QtWidgets.QPushButton(page_v2)
        self.Canasta2.setGeometry(QtCore.QRect(440, 30, 140, 30))  # Aumentado a 140 de ancho
        self.Canasta2.setObjectName("Canasta2")
        self.Canasta2.hide()
        self.Canasta2.clicked.connect(self.add_canasta2)

        self.Canasta3 = QtWidgets.QPushButton(page_v2)
        self.Canasta3.setGeometry(QtCore.QRect(440, 70, 140, 30))  # Aumentado a 140 de ancho
        self.Canasta3.setObjectName("Canasta3")
        self.Canasta3.hide()
        self.Canasta3.clicked.connect(self.add_canasta3)

        self.SuperCanasta = QtWidgets.QPushButton(page_v2)
        self.SuperCanasta.setGeometry(QtCore.QRect(440, 110, 140, 30))  # Aumentado a 140 de ancho
        self.SuperCanasta.setObjectName("SuperCanasta")
        self.SuperCanasta.hide()
        self.SuperCanasta.clicked.connect(self.add_supercanasta)

        self.CanastaFrutal = QtWidgets.QPushButton(page_v2)
        self.CanastaFrutal.setGeometry(QtCore.QRect(440, 150, 140, 30))  # Aumentado a 140 de ancho
        self.CanastaFrutal.setObjectName("CanastaFrutal")
        self.CanastaFrutal.hide()
        self.CanastaFrutal.clicked.connect(self.add_canastafrutal)

        self.CanastaAlaska = QtWidgets.QPushButton(page_v2)
        self.CanastaAlaska.setGeometry(QtCore.QRect(440, 190, 140, 30))  # Aumentado a 140 de ancho
        self.CanastaAlaska.setObjectName("CanastaAlaska")
        self.CanastaAlaska.hide()
        self.CanastaAlaska.clicked.connect(self.add_canastaalaska)

        self.CanastaPowIce = QtWidgets.QPushButton(page_v2)
        self.CanastaPowIce.setGeometry(QtCore.QRect(440, 230, 140, 30))  # Aumentado a 140 de ancho
        self.CanastaPowIce.setObjectName("CanastaPowIce")
        self.CanastaPowIce.hide()
        self.CanastaPowIce.clicked.connect(self.add_canastapowice)

        # Botones de Paletas
        self.Refrescante = QtWidgets.QPushButton(page_v2)
        self.Refrescante.setGeometry(QtCore.QRect(290, 30, 140, 30))  # Aumentado a 140 de ancho
        self.Refrescante.setObjectName("Refrescante")
        self.Refrescante.hide()
        self.Refrescante.clicked.connect(self.add_refrescante)

        self.Cremosa = QtWidgets.QPushButton(page_v2)
        self.Cremosa.setGeometry(QtCore.QRect(290, 70, 140, 30))  # Aumentado a 140 de ancho
        self.Cremosa.setObjectName("Cremosa")
        self.Cremosa.hide()
        self.Cremosa.clicked.connect(self.add_cremosa)

        self.SuperPaleta = QtWidgets.QPushButton(page_v2)
        self.SuperPaleta.setGeometry(QtCore.QRect(290, 110, 140, 30))  # Aumentado a 140 de ancho
        self.SuperPaleta.setObjectName("SuperPaleta")
        self.SuperPaleta.hide()
        self.SuperPaleta.clicked.connect(self.add_superpaleta)

        # Botones de Obleas
        self.ObleaSencilla = QtWidgets.QPushButton(page_v2)
        self.ObleaSencilla.setGeometry(QtCore.QRect(290, 30, 140, 30))  # Aumentado a 140 de ancho
        self.ObleaSencilla.setObjectName("ObleaSencilla")
        self.ObleaSencilla.hide()
        self.ObleaSencilla.clicked.connect(self.add_obleasencilla)

        self.SuperOblea = QtWidgets.QPushButton(page_v2)
        self.SuperOblea.setGeometry(QtCore.QRect(290, 70, 140, 30))  # Aumentado a 140 de ancho
        self.SuperOblea.setObjectName("SuperOblea")
        self.SuperOblea.hide()
        self.SuperOblea.clicked.connect(self.add_superoblea)

        self.ObleaPowIce = QtWidgets.QPushButton(page_v2)
        self.ObleaPowIce.setGeometry(QtCore.QRect(290, 110, 140, 30))  # Aumentado a 140 de ancho
        self.ObleaPowIce.setObjectName("ObleaPowIce")
        self.ObleaPowIce.hide()
        self.ObleaPowIce.clicked.connect(self.add_obleapowice)

        # Botones de Brownie
        self.BrownieHelado = QtWidgets.QPushButton(page_v2)
        self.BrownieHelado.setGeometry(QtCore.QRect(290, 30, 140, 30))  # Aumentado a 140 de ancho
        self.BrownieHelado.setObjectName("BrownieHelado")
        self.BrownieHelado.hide()
        self.BrownieHelado.clicked.connect(self.add_browniehelado)

        self.BrownieEspecial = QtWidgets.QPushButton(page_v2)
        self.BrownieEspecial.setGeometry(QtCore.QRect(290, 70, 140, 30))  # Aumentado a 140 de ancho
        self.BrownieEspecial.setObjectName("BrownieEspecial")
        self.BrownieEspecial.hide()
        self.BrownieEspecial.clicked.connect(self.add_brownieespecial)

        # Botones de control
        self.pushButton_2 = QtWidgets.QPushButton(page_v2)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 300, 120, 30))  # Aumentado a 120 de ancho
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.go_back)

        self.pushButton = QtWidgets.QPushButton(page_v2)
        self.pushButton.setGeometry(QtCore.QRect(270, 300, 120, 30))  # Aumentado a 120 de ancho
        self.pushButton.setObjectName("pushButton")

        self.pushButton_3 = QtWidgets.QPushButton(page_v2)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 280, 120, 30))  # Aumentado a 120 de ancho
        self.pushButton_3.setObjectName("pushButton_3")

        # Labels
        self.label = QtWidgets.QLabel(page_v2)
        self.label.setGeometry(QtCore.QRect(20, 250, 68, 22))
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(page_v2)
        self.label_2.setGeometry(QtCore.QRect(70, 250, 68, 22))
        self.label_2.setObjectName("label_2")

        # Botón Fresas Sencillas (a la derecha de Fresas)
        self.FresasSencillas = QtWidgets.QPushButton(page_v2)
        self.FresasSencillas.setGeometry(QtCore.QRect(290, 30, 140, 30))  # Primera columna a la derecha
        self.FresasSencillas.setObjectName("FresasSencillas")
        self.FresasSencillas.hide()
        self.FresasSencillas.clicked.connect(self.add_fresassencillas)

        # Botón Super Fresas (debajo de Fresas Sencillas)
        self.SuperFresas = QtWidgets.QPushButton(page_v2)
        self.SuperFresas.setGeometry(QtCore.QRect(290, 70, 140, 30))  # Segunda columna a la derecha
        self.SuperFresas.setObjectName("SuperFresas")
        self.SuperFresas.hide()
        self.SuperFresas.clicked.connect(self.add_superfresas)

        # Botones de Waffles (a la derecha de Waffles)
        self.WaffleSencillo = QtWidgets.QPushButton(page_v2)
        self.WaffleSencillo.setGeometry(QtCore.QRect(290, 30, 140, 30))  # Primera columna a la derecha
        self.WaffleSencillo.setObjectName("WaffleSencillo")
        self.WaffleSencillo.hide()
        self.WaffleSencillo.clicked.connect(self.add_wafflesencillo)

        self.WaffleFrutal = QtWidgets.QPushButton(page_v2)
        self.WaffleFrutal.setGeometry(QtCore.QRect(290, 70, 140, 30))  # Segunda columna a la derecha
        self.WaffleFrutal.setObjectName("WaffleFrutal")
        self.WaffleFrutal.hide()
        self.WaffleFrutal.clicked.connect(self.add_wafflefrutal)

        self.SuperWaffle = QtWidgets.QPushButton(page_v2)
        self.SuperWaffle.setGeometry(QtCore.QRect(290, 110, 140, 30))  # Tercera columna a la derecha
        self.SuperWaffle.setObjectName("SuperWaffle")
        self.SuperWaffle.hide()
        self.SuperWaffle.clicked.connect(self.add_superwaffle)

        self.MegaWaffles = QtWidgets.QPushButton(page_v2)
        self.MegaWaffles.setGeometry(QtCore.QRect(290, 150, 140, 30))  # Cuarta columna a la derecha
        self.MegaWaffles.setObjectName("MegaWaffles")
        self.MegaWaffles.hide()
        self.MegaWaffles.clicked.connect(self.add_megawaffles)

        self.WaffleCosmico = QtWidgets.QPushButton(page_v2)
        self.WaffleCosmico.setGeometry(QtCore.QRect(290, 190, 140, 30))  # Quinta columna a la derecha
        self.WaffleCosmico.setObjectName("WaffleCosmico")
        self.WaffleCosmico.hide()
        self.WaffleCosmico.clicked.connect(self.add_wafflecosmico)

        # Botones de Bebidas (primera columna)
        self.MalteadaSencilla = QtWidgets.QPushButton(page_v2)
        self.MalteadaSencilla.setGeometry(QtCore.QRect(290, 30, 140, 30))
        self.MalteadaSencilla.setObjectName("MalteadaSencilla")
        self.MalteadaSencilla.hide()
        self.MalteadaSencilla.clicked.connect(self.add_malteadasencilla)

        self.MalteadaSuper = QtWidgets.QPushButton(page_v2)
        self.MalteadaSuper.setGeometry(QtCore.QRect(290, 70, 140, 30))
        self.MalteadaSuper.setObjectName("MalteadaSuper")
        self.MalteadaSuper.hide()
        self.MalteadaSuper.clicked.connect(self.add_malteadasuper)

        self.Smoothie = QtWidgets.QPushButton(page_v2)
        self.Smoothie.setGeometry(QtCore.QRect(290, 110, 140, 30))
        self.Smoothie.setObjectName("Smoothie")
        self.Smoothie.hide()
        self.Smoothie.clicked.connect(self.add_smoothie)

        # Botones de Bebidas (segunda columna)
        self.Limonada = QtWidgets.QPushButton(page_v2)
        self.Limonada.setGeometry(QtCore.QRect(440, 30, 140, 30))
        self.Limonada.setObjectName("Limonada")
        self.Limonada.hide()
        self.Limonada.clicked.connect(self.add_limonada)

        self.JugoEnAgua = QtWidgets.QPushButton(page_v2)
        self.JugoEnAgua.setGeometry(QtCore.QRect(440, 70, 140, 30))
        self.JugoEnAgua.setObjectName("JugoEnAgua")
        self.JugoEnAgua.hide()
        self.JugoEnAgua.clicked.connect(self.add_jugoenagua)

        self.JugoEnLeche = QtWidgets.QPushButton(page_v2)
        self.JugoEnLeche.setGeometry(QtCore.QRect(440, 110, 140, 30))
        self.JugoEnLeche.setObjectName("JugoEnLeche")
        self.JugoEnLeche.hide()
        self.JugoEnLeche.clicked.connect(self.add_jugoenleche)

        self.GranizadoFrutal = QtWidgets.QPushButton(page_v2)
        self.GranizadoFrutal.setGeometry(QtCore.QRect(440, 150, 140, 30))
        self.GranizadoFrutal.setObjectName("GranizadoFrutal")
        self.GranizadoFrutal.hide()
        self.GranizadoFrutal.clicked.connect(self.add_granizadofrutal)

        self.GranizadoCafe = QtWidgets.QPushButton(page_v2)
        self.GranizadoCafe.setGeometry(QtCore.QRect(440, 190, 140, 30))
        self.GranizadoCafe.setObjectName("GranizadoCafe")
        self.GranizadoCafe.hide()
        self.GranizadoCafe.clicked.connect(self.add_granizadocafe)

        self.retranslateUi(page_v2)
        QtCore.QMetaObject.connectSlotsByName(page_v2)

    def hide_right_buttons(self):
        # Oculta todos los botones a la derecha de la columna principal
        self.Cono1.hide()
        self.Cono2.hide()
        self.Canasta2.hide()
        self.Canasta3.hide()
        self.SuperCanasta.hide()
        self.CanastaFrutal.hide()
        self.CanastaAlaska.hide()
        self.CanastaPowIce.hide()
        self.Refrescante.hide()
        self.Cremosa.hide()
        self.SuperPaleta.hide()
        self.ObleaSencilla.hide()
        self.SuperOblea.hide()
        self.ObleaPowIce.hide()
        self.BrownieHelado.hide()
        self.BrownieEspecial.hide()
        self.FresasSencillas.hide()
        self.SuperFresas.hide()
        self.WaffleSencillo.hide()
        self.WaffleFrutal.hide()
        self.SuperWaffle.hide()
        self.MegaWaffles.hide()
        self.WaffleCosmico.hide()
        self.MalteadaSencilla.hide()
        self.MalteadaSuper.hide()
        self.Smoothie.hide()
        self.Limonada.hide()
        self.JugoEnAgua.hide()
        self.JugoEnLeche.hide()
        self.GranizadoFrutal.hide()
        self.GranizadoCafe.hide()

    def show_cono1(self):
        self.hide_right_buttons()
        self.Cono1.show()
        self.Cono2.show()
        self.Canasta2.show()
        self.Canasta3.show()
        self.SuperCanasta.show()
        self.CanastaFrutal.show()
        self.CanastaAlaska.show()
        self.CanastaPowIce.show()

    def add_cono1(self):
        # TODO: Implement the logic to add Cono1 to the order
        pass

    def add_cono2(self):
        # TODO: Implement the logic to add Cono2 to the order
        pass

    def add_canasta2(self):
        # TODO: Implement the logic to add Canasta2 to the order
        pass

    def add_canasta3(self):
        # TODO: Implement the logic to add Canasta3 to the order
        pass

    def add_supercanasta(self):
        # TODO: Implement the logic to add SuperCanasta to the order
        pass

    def add_canastafrutal(self):
        # TODO: Implement the logic to add CanastaFrutal to the order
        pass

    def add_canastaalaska(self):
        # TODO: Implement the logic to add CanastaAlaska to the order
        pass

    def add_canastapowice(self):
        # TODO: Implement the logic to add CanastaPowIce to the order
        pass

    def show_refrescante(self):
        self.hide_right_buttons()
        self.Refrescante.show()
        self.Cremosa.show()
        self.SuperPaleta.show()

    def add_refrescante(self):
        # TODO: Implement the logic to add Refrescante to the order
        pass

    def add_cremosa(self):
        # TODO: Implement the logic to add Cremosa to the order
        pass

    def add_superpaleta(self):
        # TODO: Implement the logic to add Super Paleta to the order
        pass

    def show_obleas(self):
        self.hide_right_buttons()
        self.ObleaSencilla.show()
        self.SuperOblea.show()
        self.ObleaPowIce.show()

    def add_obleasencilla(self):
        # TODO: Implement the logic to add Oblea Sencilla to the order
        pass

    def add_superoblea(self):
        # TODO: Implement the logic to add Super oblea to the order
        pass

    def add_obleapowice(self):
        # TODO: Implement the logic to add Oblea PowIce to the order
        pass

    def show_brownie(self):
        self.hide_right_buttons()
        self.BrownieHelado.show()
        self.BrownieEspecial.show()

    def add_browniehelado(self):
        # TODO: Implement the logic to add Brownie Helado to the order
        pass

    def add_brownieespecial(self):
        # TODO: Implement the logic to add Brownie Especial to the order
        pass

    def show_fresas(self):
        self.hide_right_buttons()
        self.FresasSencillas.show()
        self.SuperFresas.show()

    def add_fresassencillas(self):
        # TODO: Implement the logic to add Fresas Sencillas to the order
        pass

    def add_superfresas(self):
        # TODO: Implement the logic to add Super Fresas to the order
        pass

    def show_waffles(self):
        self.hide_right_buttons()
        self.WaffleSencillo.show()
        self.WaffleFrutal.show()
        self.SuperWaffle.show()
        self.MegaWaffles.show()
        self.WaffleCosmico.show()

    def add_wafflesencillo(self):
        # TODO: Implement the logic to add Waffle Sencillo to the order
        pass

    def add_wafflefrutal(self):
        # TODO: Implement the logic to add Waffle Frutal to the order
        pass

    def add_superwaffle(self):
        # TODO: Implement the logic to add Super Waffle to the order
        pass

    def add_megawaffles(self):
        # TODO: Implement the logic to add Mega Waffles to the order
        pass

    def add_wafflecosmico(self):
        # TODO: Implement the logic to add Waffle Cosmico to the order
        pass

    def show_bebidas(self):
        self.hide_right_buttons()
        self.MalteadaSencilla.show()
        self.MalteadaSuper.show()
        self.Smoothie.show()
        self.Limonada.show()
        self.JugoEnAgua.show()
        self.JugoEnLeche.show()
        self.GranizadoFrutal.show()
        self.GranizadoCafe.show()

    def add_malteadasencilla(self):
        # TODO: Implement the logic to add Malteada Sencilla to the order
        pass

    def add_malteadasuper(self):
        # TODO: Implement the logic to add Malteada Super to the order
        pass

    def add_smoothie(self):
        # TODO: Implement the logic to add Smoothie to the order
        pass

    def add_limonada(self):
        # TODO: Implement the logic to add Limonada to the order
        pass

    def add_jugoenagua(self):
        # TODO: Implement the logic to add Jugo en Agua to the order
        pass

    def add_jugoenleche(self):
        # TODO: Implement the logic to add Jugo en Leche to the order
        pass

    def add_granizadofrutal(self):
        # TODO: Implement the logic to add Granizado Frutal to the order
        pass

    def add_granizadocafe(self):
        # TODO: Implement the logic to add Granizado Cafe to the order
        pass

    def go_back(self):
        try:
            # Importar aquí para evitar la importación circular
            from window.ventana_v1 import Ui_page_v1
            
            # Crear nueva ventana v1
            self.window_v1 = QtWidgets.QWidget()
            self.ui_v1 = Ui_page_v1()
            self.ui_v1.setupUi(self.window_v1)
            self.window_v1.resize(1024, 600)
            self.window_v1.show()
            
            # Cerrar la ventana actual
            self.page_v2.close()
        except Exception as e:
            print(f"Error al volver a la ventana anterior: {e}")

    def retranslateUi(self, page_v2):
        _translate = QtCore.QCoreApplication.translate
        page_v2.setWindowTitle(_translate("page_v2", "page_v2"))
        self.user_active.setText(_translate("page_v2", "usuario activo: _____"))
        self.Helados.setText(_translate("page_v2", "Helados"))
        self.Cono1.setText(_translate("page_v2", "Cono 1"))
        self.Cono2.setText(_translate("page_v2", "Cono 2"))
        self.Canasta2.setText(_translate("page_v2", "Canasta 2"))
        self.Canasta3.setText(_translate("page_v2", "Canasta 3"))
        self.SuperCanasta.setText(_translate("page_v2", "Super Canasta"))
        self.CanastaFrutal.setText(_translate("page_v2", "Canasta Frutal"))
        self.CanastaAlaska.setText(_translate("page_v2", "Canasta Alaska"))
        self.CanastaPowIce.setText(_translate("page_v2", "Canasta PowIce"))
        self.Paletas.setText(_translate("page_v2", "Paletas"))
        self.Refrescante.setText(_translate("page_v2", "Refrescante"))
        self.Cremosa.setText(_translate("page_v2", "Cremosa"))
        self.SuperPaleta.setText(_translate("page_v2", "Super Paleta"))
        self.Obleas.setText(_translate("page_v2", "Obleas"))
        self.ObleaSencilla.setText(_translate("page_v2", "Oblea Sencilla"))
        self.SuperOblea.setText(_translate("page_v2", "Super Oblea"))
        self.ObleaPowIce.setText(_translate("page_v2", "Oblea PowIce"))
        self.Brownie.setText(_translate("page_v2", "Brownie"))
        self.BrownieHelado.setText(_translate("page_v2", "Brownie Helado"))
        self.BrownieEspecial.setText(_translate("page_v2", "Brownie Especial"))
        self.Waffles.setText(_translate("page_v2", "Waffles"))
        self.Fresas.setText(_translate("page_v2", "Fresas"))
        self.Bebidas.setText(_translate("page_v2", "Bebidas"))
        self.MalteadaSencilla.setText(_translate("page_v2", "Malteada Sencilla"))
        self.MalteadaSuper.setText(_translate("page_v2", "Malteada Super"))
        self.Smoothie.setText(_translate("page_v2", "Smoothie"))
        self.Limonada.setText(_translate("page_v2", "Limonada"))
        self.JugoEnAgua.setText(_translate("page_v2", "Jugo En Agua"))
        self.JugoEnLeche.setText(_translate("page_v2", "Jugo En Leche"))
        self.GranizadoFrutal.setText(_translate("page_v2", "Granizado Frutal"))
        self.GranizadoCafe.setText(_translate("page_v2", "Granizado Cafe"))
        self.Otros.setText(_translate("page_v2", "Otros"))
        self.pushButton_2.setText(_translate("page_v2", "Atrás"))
        self.pushButton.setText(_translate("page_v2", "OK"))
        self.label.setText(_translate("page_v2", "Total:"))
        self.label_2.setText(_translate("page_v2", "111111"))
        self.pushButton_3.setText(_translate("page_v2", "Borrar"))
        self.FresasSencillas.setText(_translate("page_v2", "Fresas Sencillas"))
        self.SuperFresas.setText(_translate("page_v2", "Super Fresas"))
        self.WaffleSencillo.setText(_translate("page_v2", "Waffle Sencillo"))
        self.WaffleFrutal.setText(_translate("page_v2", "Waffle Frutal"))
        self.SuperWaffle.setText(_translate("page_v2", "Super Waffle"))
        self.MegaWaffles.setText(_translate("page_v2", "Mega Waffles"))
        self.WaffleCosmico.setText(_translate("page_v2", "Waffle Cosmico"))

    def set_user_active(self, user_name):
        self.user_active.setText(f"usuario activo: {user_name}")  # Update user_active label


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    page_v2 = QtWidgets.QDialog()
    ui = Ui_page_v2()
    ui.setupUi(page_v2)
    page_v2.show()
    sys.exit(app.exec_())

