# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pow_ice_page_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5.QtWidgets import QTableWidgetItem
from window.ventana_v3 import Ui_page_v3  # Agregar esta línea
from datetime import datetime
from PyQt5.QtCore import QTimer
from db_helper import get_product  # Cache de productos - evita conexiones repetidas


class Ui_page_v2(object):
    # Variables de clase para gestionar ventanas
    mesa_windows = {}  # Diccionario para almacenar las ventanas de cada mesa (2, 3, 4)
    main_window = None  # Referencia a la ventana principal (Mesa 1)
    open_windows = 0  # Contador de ventanas abiertas
    
    def __init__(self):
        self.mesa_number = 1  # Por defecto es Mesa 1

    @classmethod
    def reset_window_counters(cls):
        """Reinicia todos los contadores de ventanas"""
        cls.main_window = None
        cls.mesa_windows.clear()

    def setupUi(self, page_v2):
        # Reiniciar contadores si es la ventana principal (Mesa 1)
        if not hasattr(self, 'mesa_number'):
            Ui_page_v2.reset_window_counters()
            self.mesa_number = 1  # Default mesa number
            
        self.page_v2 = page_v2  # Guardar referencia a la ventana principal
        page_v2.setObjectName("page_v2")
        page_v2.resize(1024, 600)
        page_v2.setWindowFlags(QtCore.Qt.Window | QtCore.Qt.CustomizeWindowHint | QtCore.Qt.WindowTitleHint)  # Disable close button
        page_v2.setWindowTitle("Pedido 1")  # Establecer título de la ventana principal

        # Crear frame de fondo
        self.background_frame = QtWidgets.QFrame(page_v2)
        self.background_frame.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.background_frame.setStyleSheet("background-color: #E6F3FF;")  # Mismo color que el fondo
        self.background_frame.lower()  # Enviar al fondo

        # Establecer el color de fondo de la ventana (tono azul claro)
        page_v2.setStyleSheet("""
            QWidget {
                background-color: #E6F3FF;  /* Azul pastel claro */
            }
            QPushButton {
                background-color: #4A90E2;  /* Azul medio */
                border: 3px solid #2C5282;  /* Azul oscuro */
                border-radius: 15px;
                color: white;  /* Texto blanco para mejor contraste */
                padding: 5px;
                font-size: 18px;
            }
            QPushButton:hover {
                background-color: #2C5282;  /* Azul oscuro al pasar el mouse */
                color: white;
            }
            QLabel {
                color: #1A365D;  /* Azul muy oscuro para el texto */
                font-size: 18px;
            }
            QTableWidget {
                background-color: white;
                border: 3px solid #4A90E2;
                border-radius: 10px;
                gridline-color: #E6F3FF;
                font-size: 14px;  /* <-- Reducido de 20px a 14px */
            }
            QTableWidget::item {
                padding: 5px;
                font-size: 14px;  /* <-- Reducido de 20px a 14px */
            }
            QTableWidget::item:selected {
                background-color: #4A90E2;
                color: white;
                font-size: 14px;  /* <-- Reducido de 20px a 14px */
            }
            QHeaderView::section {
                background-color: #4A90E2;
                color: white;
                padding: 5px;
                border: 1px solid #2C5282;
                font-size: 20px;
            }
            QLineEdit {
                background-color: white;
                border: 2px solid #4A90E2;
                border-radius: 10px;
                padding: 5px;
                color: #1A365D;
                font-size: 20px;
            }
            QLineEdit:focus {
                border: 2px solid #2C5282;
                background-color: #F0F7FF;
            }
            QRadioButton {
                color: #1A365D;
                font-size: 20px;
            }
            QRadioButton::indicator {
                width: 20px;
                height: 20px;
            }
            QRadioButton::indicator:unchecked {
                border: 2px solid #4A90E2;
                background-color: white;
                border-radius: 10px;
            }
            QRadioButton::indicator:checked {
                border: 2px solid #2C5282;
                background-color: #4A90E2;
                border-radius: 10px;
            }
        """)

        # Configurar fuente base
        base_font = QtGui.QFont()
        base_font.setPointSize(14)  # Tamaño de fuente base

        # Guardar referencia a la ventana principal si es Mesa 1
        if not Ui_page_v2.main_window:
            Ui_page_v2.main_window = page_v2
            Ui_page_v2.mesa_windows[1] = page_v2  # Agregar también al diccionario de ventanas
        
        # Increment window counter when creating a new window
        Ui_page_v2.open_windows += 1
        
        # Conectar el evento de cierre
        page_v2.closeEvent = self.closeEvent
        
        # Label para usuario activo
        self.user_active = QtWidgets.QLabel(page_v2)
        self.user_active.setGeometry(QtCore.QRect(20, 10, 400, 30))  # Movido arriba de la tabla
        self.user_active.setObjectName("user_active")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.user_active.setFont(font)
        
        # Label para mostrar el número de mesa
        self.mesa_label = QtWidgets.QLabel(page_v2)
        self.mesa_label.setGeometry(QtCore.QRect(460, 30, 100, 40))
        self.mesa_label.setObjectName("mesa_label")
        self.mesa_label.setText(f"Pedido {self.mesa_number}")
        self.mesa_label.setFont(base_font)
        self.mesa_label.setStyleSheet("""
            QLabel {
                color: #1A365D;  /* Azul muy oscuro para el texto */
                font-weight: bold;
                background-color: transparent;
            }
        """)
        
        # Configurar TableView
        self.tableView = QtWidgets.QTableWidget(page_v2)
        self.tableView.setGeometry(QtCore.QRect(20, 50, 400, 400))  # Ajustada la posición Y para dejar espacio al label
        self.tableView.setObjectName("tableView")
        self.tableView.setColumnCount(3)
        self.tableView.setHorizontalHeaderLabels(["Producto", "Precio", "Cant"])
        self.tableView.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.tableView.itemChanged.connect(self.calculate_total)  # Conectar el evento de cambio de celda
        # Ajustar altura de filas para texto grande
        self.tableView.verticalHeader().setDefaultSectionSize(40)
        # Reducir el ancho de la columna 'Cant'
        self.tableView.setColumnWidth(2, 60)  # <-- Reducir el ancho de la columna 'Cant'

        # Botones principales (columna izquierda) - Movidos a la derecha del TableView
        self.Helados = QtWidgets.QPushButton(page_v2)
        self.Helados.setGeometry(QtCore.QRect(440, 40, 120, 30))
        self.Helados.setObjectName("Helados")
        self.Helados.clicked.connect(self.show_cono1)

        self.Paletas = QtWidgets.QPushButton(page_v2)
        self.Paletas.setGeometry(QtCore.QRect(440, 80, 120, 30))
        self.Paletas.setObjectName("Paletas")
        self.Paletas.clicked.connect(self.show_refrescante)

        self.Obleas = QtWidgets.QPushButton(page_v2)
        self.Obleas.setGeometry(QtCore.QRect(440, 120, 120, 30))
        self.Obleas.setObjectName("Obleas")
        self.Obleas.clicked.connect(self.show_obleas)

        self.Brownie = QtWidgets.QPushButton(page_v2)
        self.Brownie.setGeometry(QtCore.QRect(440, 160, 120, 30))
        self.Brownie.setObjectName("Brownie")
        self.Brownie.clicked.connect(self.show_brownie)

        self.Fresas = QtWidgets.QPushButton(page_v2)
        self.Fresas.setGeometry(QtCore.QRect(440, 200, 120, 30))
        self.Fresas.setObjectName("Fresas")
        self.Fresas.clicked.connect(self.show_fresas)

        self.Waffles = QtWidgets.QPushButton(page_v2)
        self.Waffles.setGeometry(QtCore.QRect(440, 240, 120, 30))
        self.Waffles.setObjectName("Waffles")
        self.Waffles.clicked.connect(self.show_waffles)

        self.Bebidas = QtWidgets.QPushButton(page_v2)
        self.Bebidas.setGeometry(QtCore.QRect(440, 280, 120, 30))
        self.Bebidas.setObjectName("Bebidas")
        self.Bebidas.clicked.connect(self.show_bebidas)

        self.Otros = QtWidgets.QPushButton(page_v2)
        self.Otros.setGeometry(QtCore.QRect(440, 320, 120, 30))
        self.Otros.setObjectName("Otros")
        self.Otros.clicked.connect(self.show_otros)

        # Botones de Helados (segunda columna) - Movidos más a la derecha
        self.Cono1 = QtWidgets.QPushButton(page_v2)
        self.Cono1.setGeometry(QtCore.QRect(580, 40, 200, 30))  # Aumentado el ancho a 200
        self.Cono1.setObjectName("Cono1")
        self.Cono1.hide()
        self.Cono1.clicked.connect(self.add_cono1)

        self.Cono2 = QtWidgets.QPushButton(page_v2)
        self.Cono2.setGeometry(QtCore.QRect(580, 80, 200, 30))  # Aumentado el ancho a 200
        self.Cono2.setObjectName("Cono2")
        self.Cono2.hide()
        self.Cono2.clicked.connect(self.add_cono2)

        # Botones de Canasta (tercera columna) - Movidos más a la derecha
        self.Canasta1 = QtWidgets.QPushButton(page_v2)
        self.Canasta1.setGeometry(QtCore.QRect(780, 40, 200, 30))  # Aumentado el ancho a 200
        self.Canasta1.setObjectName("Canasta1")
        self.Canasta1.hide()
        self.Canasta1.clicked.connect(self.add_canasta1)

        self.Canasta2 = QtWidgets.QPushButton(page_v2)
        self.Canasta2.setGeometry(QtCore.QRect(780, 80, 200, 30))  # Aumentado el ancho a 200
        self.Canasta2.setObjectName("Canasta2")
        self.Canasta2.hide()
        self.Canasta2.clicked.connect(self.add_canasta2)

        self.Canasta3 = QtWidgets.QPushButton(page_v2)
        self.Canasta3.setGeometry(QtCore.QRect(780, 120, 200, 30))  # Aumentado el ancho a 200
        self.Canasta3.setObjectName("Canasta3")
        self.Canasta3.hide()
        self.Canasta3.clicked.connect(self.add_canasta3)

        self.SuperCanasta = QtWidgets.QPushButton(page_v2)
        self.SuperCanasta.setGeometry(QtCore.QRect(780, 160, 200, 30))  # Aumentado el ancho a 200
        self.SuperCanasta.setObjectName("SuperCanasta")
        self.SuperCanasta.hide()
        self.SuperCanasta.clicked.connect(self.add_supercanasta)

        self.CanastaFrutal = QtWidgets.QPushButton(page_v2)
        self.CanastaFrutal.setGeometry(QtCore.QRect(780, 200, 200, 30))  # Aumentado el ancho a 200
        self.CanastaFrutal.setObjectName("CanastaFrutal")
        self.CanastaFrutal.hide()
        self.CanastaFrutal.clicked.connect(self.add_canastafrutal)

        self.CanastaAlaska = QtWidgets.QPushButton(page_v2)
        self.CanastaAlaska.setGeometry(QtCore.QRect(780, 240, 200, 30))  # Aumentado el ancho a 200
        self.CanastaAlaska.setObjectName("CanastaAlaska")
        self.CanastaAlaska.hide()
        self.CanastaAlaska.clicked.connect(self.add_canastaalaska)

        self.CanastaPowIce = QtWidgets.QPushButton(page_v2)
        self.CanastaPowIce.setGeometry(QtCore.QRect(780, 280, 200, 30))  # Aumentado el ancho a 200
        self.CanastaPowIce.setObjectName("CanastaPowIce")
        self.CanastaPowIce.hide()
        self.CanastaPowIce.clicked.connect(self.add_canastapowice)

        # Botón Canasta Infantil
        self.CanastaInfantil = QtWidgets.QPushButton(page_v2)
        self.CanastaInfantil.setGeometry(QtCore.QRect(780, 320, 200, 30))  # Debajo de CanastaPowIce
        self.CanastaInfantil.setObjectName("CanastaInfantil")
        self.CanastaInfantil.setText("CANASTA INFANTIL")
        self.CanastaInfantil.hide()
        self.CanastaInfantil.clicked.connect(self.add_canastainfantil)

        # Botones de control - Movidos a la parte inferior
        self.pushButton_2 = QtWidgets.QPushButton(page_v2)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 530, 120, 30))  # Bajado a y=530
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.go_back)

        self.pushButton = QtWidgets.QPushButton(page_v2)
        self.pushButton.setGeometry(QtCore.QRect(190, 530, 120, 30))  # Bajado a y=530
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.open_v3)  # Conectar el botón OK con la nueva función

        self.plusButton = QtWidgets.QPushButton(page_v2)
        self.plusButton.setGeometry(QtCore.QRect(440, 490, 120, 30))
        self.plusButton.setObjectName("plusButton")
        self.plusButton.clicked.connect(self.open_new_window)

        self.minusButton = QtWidgets.QPushButton(page_v2)
        self.minusButton.setGeometry(QtCore.QRect(580, 490, 120, 30))
        self.minusButton.setObjectName("minusButton")
        self.minusButton.clicked.connect(self.close_current_window)

        # Botón mesa 3
        self.mesa3Button = QtWidgets.QPushButton(page_v2)
        self.mesa3Button.setGeometry(QtCore.QRect(740, 490, 120, 30))
        self.mesa3Button.setObjectName("mesa3Button")
        self.mesa3Button.clicked.connect(self.open_mesa3)

        # Botón mesa 4
        self.mesa4Button = QtWidgets.QPushButton(page_v2)
        self.mesa4Button.setGeometry(QtCore.QRect(880, 490, 120, 30))
        self.mesa4Button.setObjectName("mesa4Button")
        self.mesa4Button.clicked.connect(self.open_mesa4)

        self.pushButton_3 = QtWidgets.QPushButton(page_v2)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 450, 120, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.delete_last_row)

        # Labels - Movidos a la parte inferior
        self.label = QtWidgets.QLabel(page_v2)
        self.label.setGeometry(QtCore.QRect(20, 490, 68, 22))
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(page_v2)
        self.label_2.setGeometry(QtCore.QRect(90, 490, 68, 22))
        self.label_2.setObjectName("label_2")

        # Botones de Paletas - Ajustados a la nueva posición
        self.Refrescante = QtWidgets.QPushButton(page_v2)
        self.Refrescante.setGeometry(QtCore.QRect(580, 40, 200, 30))  # Aumentado el ancho a 200
        self.Refrescante.setObjectName("Refrescante")
        self.Refrescante.hide()
        self.Refrescante.clicked.connect(self.add_refrescante)

        self.Cremosa = QtWidgets.QPushButton(page_v2)
        self.Cremosa.setGeometry(QtCore.QRect(580, 80, 200, 30))  # Aumentado el ancho a 200
        self.Cremosa.setObjectName("Cremosa")
        self.Cremosa.hide()
        self.Cremosa.clicked.connect(self.add_cremosa)

        self.SuperPaleta = QtWidgets.QPushButton(page_v2)
        self.SuperPaleta.setGeometry(QtCore.QRect(580, 120, 200, 30))  # Aumentado el ancho a 200
        self.SuperPaleta.setObjectName("SuperPaleta")
        self.SuperPaleta.hide()
        self.SuperPaleta.clicked.connect(self.add_superpaleta)

        # Botones de Obleas - Ajustados a la nueva posición
        self.ObleaSencilla = QtWidgets.QPushButton(page_v2)
        self.ObleaSencilla.setGeometry(QtCore.QRect(580, 40, 200, 30))  # Aumentado el ancho a 200
        self.ObleaSencilla.setObjectName("ObleaSencilla")
        self.ObleaSencilla.hide()
        self.ObleaSencilla.clicked.connect(self.add_obleasencilla)

        self.SuperOblea = QtWidgets.QPushButton(page_v2)
        self.SuperOblea.setGeometry(QtCore.QRect(580, 80, 200, 30))  # Aumentado el ancho a 200
        self.SuperOblea.setObjectName("SuperOblea")
        self.SuperOblea.hide()
        self.SuperOblea.clicked.connect(self.add_superoblea)

        self.ObleaPowIce = QtWidgets.QPushButton(page_v2)
        self.ObleaPowIce.setGeometry(QtCore.QRect(580, 120, 200, 30))  # Aumentado el ancho a 200
        self.ObleaPowIce.setObjectName("ObleaPowIce")
        self.ObleaPowIce.hide()
        self.ObleaPowIce.clicked.connect(self.add_obleapowice)

        # Botones de Brownie - Ajustados a la nueva posición
        self.BrownieHelado = QtWidgets.QPushButton(page_v2)
        self.BrownieHelado.setGeometry(QtCore.QRect(580, 40, 200, 30))  # Aumentado el ancho a 200
        self.BrownieHelado.setObjectName("BrownieHelado")
        self.BrownieHelado.hide()
        self.BrownieHelado.clicked.connect(self.add_browniehelado)

        self.BrownieEspecial = QtWidgets.QPushButton(page_v2)
        self.BrownieEspecial.setGeometry(QtCore.QRect(580, 80, 200, 30))  # Aumentado el ancho a 200
        self.BrownieEspecial.setObjectName("BrownieEspecial")
        self.BrownieEspecial.hide()
        self.BrownieEspecial.clicked.connect(self.add_brownieespecial)

        self.BrownieNevado = QtWidgets.QPushButton(page_v2)
        self.BrownieNevado.setGeometry(QtCore.QRect(580, 120, 200, 30))  # Aumentado el ancho a 200
        self.BrownieNevado.setObjectName("BrownieNevado")
        self.BrownieNevado.hide()
        self.BrownieNevado.clicked.connect(self.add_brownie_nevado)

        # Botones de Fresas - Ajustados a la nueva posición
        self.FresasSencillas = QtWidgets.QPushButton(page_v2)
        self.FresasSencillas.setGeometry(QtCore.QRect(580, 40, 200, 30))  # Aumentado el ancho a 200
        self.FresasSencillas.setObjectName("FresasSencillas")
        self.FresasSencillas.hide()
        self.FresasSencillas.clicked.connect(self.add_fresassencillas)

        self.SuperFresas = QtWidgets.QPushButton(page_v2)
        self.SuperFresas.setGeometry(QtCore.QRect(580, 80, 200, 30))  # Aumentado el ancho a 200
        self.SuperFresas.setObjectName("SuperFresas")
        self.SuperFresas.hide()
        self.SuperFresas.clicked.connect(self.add_superfresas)

        # Botones de Waffles - Ajustados a la nueva posición
        self.WaffleSencillo = QtWidgets.QPushButton(page_v2)
        self.WaffleSencillo.setGeometry(QtCore.QRect(580, 40, 200, 30))  # Aumentado el ancho a 200
        self.WaffleSencillo.setObjectName("WaffleSencillo")
        self.WaffleSencillo.hide()
        self.WaffleSencillo.clicked.connect(self.add_wafflesencillo)

        self.WaffleFrutal = QtWidgets.QPushButton(page_v2)
        self.WaffleFrutal.setGeometry(QtCore.QRect(580, 80, 200, 30))  # Aumentado el ancho a 200
        self.WaffleFrutal.setObjectName("WaffleFrutal")
        self.WaffleFrutal.hide()
        self.WaffleFrutal.clicked.connect(self.add_wafflefrutal)

        self.SuperWaffle = QtWidgets.QPushButton(page_v2)
        self.SuperWaffle.setGeometry(QtCore.QRect(580, 120, 200, 30))  # Aumentado el ancho a 200
        self.SuperWaffle.setObjectName("SuperWaffle")
        self.SuperWaffle.hide()
        self.SuperWaffle.clicked.connect(self.add_superwaffle)

        self.MegaWaffles = QtWidgets.QPushButton(page_v2)
        self.MegaWaffles.setGeometry(QtCore.QRect(580, 160, 200, 30))  # Aumentado el ancho a 200
        self.MegaWaffles.setObjectName("MegaWaffles")
        self.MegaWaffles.hide()
        self.MegaWaffles.clicked.connect(self.add_megawaffles)

        self.WaffleCosmico = QtWidgets.QPushButton(page_v2)
        self.WaffleCosmico.setGeometry(QtCore.QRect(580, 200, 200, 30))  # Aumentado el ancho a 200
        self.WaffleCosmico.setObjectName("WaffleCosmico")
        self.WaffleCosmico.hide()
        self.WaffleCosmico.clicked.connect(self.add_wafflecosmico)

        # Botones de Bebidas - Ajustados a la nueva posición
        self.MalteadaSencilla = QtWidgets.QPushButton(page_v2)
        self.MalteadaSencilla.setGeometry(QtCore.QRect(580, 40, 200, 30))  # Aumentado el ancho a 200
        self.MalteadaSencilla.setObjectName("MalteadaSencilla")
        self.MalteadaSencilla.hide()
        self.MalteadaSencilla.clicked.connect(self.add_malteadasencilla)

        self.MalteadaSuper = QtWidgets.QPushButton(page_v2)
        self.MalteadaSuper.setGeometry(QtCore.QRect(580, 80, 200, 30))  # Aumentado el ancho a 200
        self.MalteadaSuper.setObjectName("MalteadaSuper")
        self.MalteadaSuper.hide()
        self.MalteadaSuper.clicked.connect(self.add_malteadasuper)

        self.Smoothie = QtWidgets.QPushButton(page_v2)
        self.Smoothie.setGeometry(QtCore.QRect(580, 120, 200, 30))  # Aumentado el ancho a 200
        self.Smoothie.setObjectName("Smoothie")
        self.Smoothie.hide()
        self.Smoothie.clicked.connect(self.add_smoothie)

        self.Limonada = QtWidgets.QPushButton(page_v2)
        self.Limonada.setGeometry(QtCore.QRect(780, 40, 200, 30))  # Aumentado el ancho a 200
        self.Limonada.setObjectName("Limonada")
        self.Limonada.hide()
        self.Limonada.clicked.connect(self.add_limonada)

        self.JugoEnAgua = QtWidgets.QPushButton(page_v2)
        self.JugoEnAgua.setGeometry(QtCore.QRect(780, 80, 200, 30))  # Aumentado el ancho a 200
        self.JugoEnAgua.setObjectName("JugoEnAgua")
        self.JugoEnAgua.hide()
        self.JugoEnAgua.clicked.connect(self.add_jugoenagua)

        self.JugoEnLeche = QtWidgets.QPushButton(page_v2)
        self.JugoEnLeche.setGeometry(QtCore.QRect(780, 120, 200, 30))  # Aumentado el ancho a 200
        self.JugoEnLeche.setObjectName("JugoEnLeche")
        self.JugoEnLeche.hide()
        self.JugoEnLeche.clicked.connect(self.add_jugoenleche)

        self.GranizadoFrutal = QtWidgets.QPushButton(page_v2)
        self.GranizadoFrutal.setGeometry(QtCore.QRect(780, 160, 200, 30))  # Aumentado el ancho a 200
        self.GranizadoFrutal.setObjectName("GranizadoFrutal")
        self.GranizadoFrutal.hide()
        self.GranizadoFrutal.clicked.connect(self.add_granizadofrutal)

        self.GranizadoCafe = QtWidgets.QPushButton(page_v2)
        self.GranizadoCafe.setGeometry(QtCore.QRect(780, 200, 200, 30))  # Aumentado el ancho a 200
        self.GranizadoCafe.setObjectName("GranizadoCafe")
        self.GranizadoCafe.hide()
        self.GranizadoCafe.clicked.connect(self.add_granizadocafe)

        # Botones de Otros - Ajustados a la nueva posición
        self.BananaSplit = QtWidgets.QPushButton(page_v2)
        self.BananaSplit.setGeometry(QtCore.QRect(580, 40, 200, 30))  # Aumentado el ancho a 200
        self.BananaSplit.setObjectName("BananaSplit")
        self.BananaSplit.hide()
        self.BananaSplit.clicked.connect(self.add_bananasplit)

        self.Topping = QtWidgets.QPushButton(page_v2)
        self.Topping.setGeometry(QtCore.QRect(580, 80, 200, 30))  # Aumentado el ancho a 200
        self.Topping.setObjectName("Topping")
        self.Topping.hide()
        self.Topping.clicked.connect(self.add_topping)

        self.Empaque = QtWidgets.QPushButton(page_v2)
        self.Empaque.setGeometry(QtCore.QRect(580, 120, 200, 30))  # Aumentado el ancho a 200
        self.Empaque.setObjectName("Empaque")
        self.Empaque.hide()
        self.Empaque.clicked.connect(self.add_empaque)

        self.Litro = QtWidgets.QPushButton(page_v2)
        self.Litro.setGeometry(QtCore.QRect(580, 160, 200, 30))  # Aumentado el ancho a 200
        self.Litro.setObjectName("Litro")
        self.Litro.hide()
        self.Litro.clicked.connect(self.add_litro)

        self.MedioLitro = QtWidgets.QPushButton(page_v2)
        self.MedioLitro.setGeometry(QtCore.QRect(580, 200, 200, 30))  # Aumentado el ancho a 200
        self.MedioLitro.setObjectName("MedioLitro")
        self.MedioLitro.hide()
        self.MedioLitro.clicked.connect(self.add_medio_litro)

        self.LitroPrem = QtWidgets.QPushButton(page_v2)
        self.LitroPrem.setGeometry(QtCore.QRect(580, 240, 200, 30))  # Aumentado el ancho a 200
        self.LitroPrem.setObjectName("LitroPrem")
        self.LitroPrem.hide()
        self.LitroPrem.clicked.connect(self.add_litro_prem)

        self.MedioLitroPrem = QtWidgets.QPushButton(page_v2)
        self.MedioLitroPrem.setGeometry(QtCore.QRect(580, 280, 200, 30))  # Aumentado el ancho a 200
        self.MedioLitroPrem.setObjectName("MedioLitroPrem")
        self.MedioLitroPrem.hide()
        self.MedioLitroPrem.clicked.connect(self.add_medio_litro_prem)

        self.TintoAmericano = QtWidgets.QPushButton(page_v2)
        self.TintoAmericano.setGeometry(QtCore.QRect(780, 40, 200, 30))  # Aumentado el ancho a 200
        self.TintoAmericano.setObjectName("TintoAmericano")
        self.TintoAmericano.hide()
        self.TintoAmericano.clicked.connect(self.add_tintoamericano)

        self.Cappuccino = QtWidgets.QPushButton(page_v2)
        self.Cappuccino.setGeometry(QtCore.QRect(780, 80, 200, 30))  # Aumentado el ancho a 200
        self.Cappuccino.setObjectName("Cappuccino")
        self.Cappuccino.hide()
        self.Cappuccino.clicked.connect(self.add_cappuccino)

        self.Mochaccino = QtWidgets.QPushButton(page_v2)
        self.Mochaccino.setGeometry(QtCore.QRect(780, 120, 200, 30))  # Aumentado el ancho a 200
        self.Mochaccino.setObjectName("Mochaccino")
        self.Mochaccino.hide()
        self.Mochaccino.clicked.connect(self.add_mochaccino)

        self.Aromatica = QtWidgets.QPushButton(page_v2)
        self.Aromatica.setGeometry(QtCore.QRect(780, 160, 200, 30))  # Aumentado el ancho a 200
        self.Aromatica.setObjectName("Aromatica")
        self.Aromatica.hide()
        self.Aromatica.clicked.connect(self.add_aromatica)

        self.AguaBotella = QtWidgets.QPushButton(page_v2)
        self.AguaBotella.setGeometry(QtCore.QRect(780, 200, 200, 30))  # Aumentado el ancho a 200
        self.AguaBotella.setObjectName("AguaBotella")
        self.AguaBotella.hide()
        self.AguaBotella.clicked.connect(self.add_agua_botella)

        self.retranslateUi(page_v2)
        QtCore.QMetaObject.connectSlotsByName(page_v2)

        # Mostrar la marca visual para el pedido activo (incluye Pedido 1)
        QTimer.singleShot(0, self.show_pedido_marker)

    def add_product_to_table(self, product_name_lower):
        """Agrega producto a la tabla usando cache (sin abrir conexión DB)."""
        result = get_product(product_name_lower)
        if not result:
            return
        product_name, price = result
        price_int = int(price)
        # Bloquear señales para evitar múltiples calculate_total
        self.tableView.blockSignals(True)
        try:
            found = False
            for row in range(self.tableView.rowCount()):
                item = self.tableView.item(row, 0)
                if item and item.text() == product_name:
                    cant_item = self.tableView.item(row, 2)
                    if cant_item:
                        current_cant = int(cant_item.text())
                        self.tableView.setItem(row, 2, QTableWidgetItem(str(current_cant + 1)))
                    found = True
                    break
            if not found:
                row_position = self.tableView.rowCount()
                self.tableView.insertRow(row_position)
                self.tableView.setItem(row_position, 0, QTableWidgetItem(product_name))
                self.tableView.setItem(row_position, 1, QTableWidgetItem(str(price_int)))
                self.tableView.setItem(row_position, 2, QTableWidgetItem("1"))
        finally:
            self.tableView.blockSignals(False)
        self.calculate_total()

    def hide_right_buttons(self):
        # Oculta todos los botones a la derecha de la columna principal
        self.Cono1.hide()
        self.Cono2.hide()
        self.Canasta1.hide()
        self.Canasta2.hide()
        self.Canasta3.hide()
        self.SuperCanasta.hide()
        self.CanastaFrutal.hide()
        self.CanastaAlaska.hide()
        self.CanastaPowIce.hide()
        self.CanastaInfantil.hide()
        self.Refrescante.hide()
        self.Cremosa.hide()
        self.SuperPaleta.hide()
        self.ObleaSencilla.hide()
        self.SuperOblea.hide()
        self.ObleaPowIce.hide()
        self.BrownieHelado.hide()
        self.BrownieEspecial.hide()
        self.BrownieNevado.hide()
        self.FresasSencillas.hide()
        self.SuperFresas.hide()
        self.WaffleSencillo.hide()
        self.WaffleFrutal.hide()
        self.SuperWaffle.hide()
        self.MegaWaffles.hide()
        self.WaffleCosmico.hide()
        self.MalteadaSencilla.hide()
        self.MalteadaSuper.hide()
        self.Smoothie.hide()
        self.Limonada.hide()
        self.JugoEnAgua.hide()
        self.JugoEnLeche.hide()
        self.GranizadoFrutal.hide()
        self.GranizadoCafe.hide()
        self.BananaSplit.hide()
        self.Topping.hide()
        self.Empaque.hide()
        self.Litro.hide()
        self.MedioLitro.hide()
        self.LitroPrem.hide()
        self.MedioLitroPrem.hide()
        self.TintoAmericano.hide()
        self.Cappuccino.hide()
        self.Mochaccino.hide()
        self.Aromatica.hide()
        self.AguaBotella.hide()

    def show_cono1(self):
        self.hide_right_buttons()
        self.Cono1.show()
        self.Cono2.show()
        self.Canasta1.show()
        self.Canasta2.show()
        self.Canasta3.show()
        self.SuperCanasta.show()
        self.CanastaFrutal.show()
        self.CanastaAlaska.show()
        self.CanastaPowIce.show()
        self.CanastaInfantil.show()
    def add_canastainfantil(self):
        self.add_product_to_table('canasta infantil')

    def add_cono1(self):
        self.add_product_to_table('cono 1')

    def add_cono2(self):
        self.add_product_to_table('cono 2')

    def add_canasta1(self):
        self.add_product_to_table('canasta 1')

    def add_canasta2(self):
        self.add_product_to_table('canasta 2')

    def add_canasta3(self):
        self.add_product_to_table('canasta 3')

    def add_supercanasta(self):
        self.add_product_to_table('super canasta')

    def add_canastafrutal(self):
        self.add_product_to_table('canasta frutal')

    def add_canastaalaska(self):
        self.add_product_to_table('canasta alaska')

    def add_canastapowice(self):
        self.add_product_to_table('canasta powice')

    def show_refrescante(self):
        self.hide_right_buttons()
        self.Refrescante.show()
        self.Cremosa.show()
        self.SuperPaleta.show()

    def add_refrescante(self):
        self.add_product_to_table('refrescante')

    def add_cremosa(self):
        self.add_product_to_table('cremosa')

    def add_superpaleta(self):
        self.add_product_to_table('super paleta')

    def show_obleas(self):
        self.hide_right_buttons()
        self.ObleaSencilla.show()
        self.SuperOblea.show()
        self.ObleaPowIce.show()

    def add_obleasencilla(self):
        self.add_product_to_table('oblea sencilla')

    def add_superoblea(self):
        self.add_product_to_table('super oblea')

    def add_obleapowice(self):
        self.add_product_to_table('oblea powice')

    def show_brownie(self):
        self.hide_right_buttons()
        self.BrownieHelado.show()
        self.BrownieEspecial.show()
        self.BrownieNevado.show()

    def add_browniehelado(self):
        self.add_product_to_table('brownie helado')

    def add_brownieespecial(self):
        self.add_product_to_table('brownie especial')

    def add_brownie_nevado(self):
        self.add_product_to_table('brownie nevado')

    def show_fresas(self):
        self.hide_right_buttons()
        self.FresasSencillas.show()
        self.SuperFresas.show()

    def add_fresassencillas(self):
        self.add_product_to_table('fresas sencillas')

    def add_superfresas(self):
        self.add_product_to_table('super fresas')

    def show_waffles(self):
        self.hide_right_buttons()
        self.WaffleSencillo.show()
        self.WaffleFrutal.show()
        self.SuperWaffle.show()
        self.MegaWaffles.show()
        self.WaffleCosmico.show()

    def add_wafflesencillo(self):
        self.add_product_to_table('waffle sencillo')

    def add_wafflefrutal(self):
        self.add_product_to_table('waffle frutal')

    def add_superwaffle(self):
        self.add_product_to_table('super waffle')

    def add_megawaffles(self):
        self.add_product_to_table('mega waffles')

    def add_wafflecosmico(self):
        self.add_product_to_table('waffle cosmico')

    def show_bebidas(self):
        self.hide_right_buttons()
        self.MalteadaSencilla.show()
        self.MalteadaSuper.show()
        self.Smoothie.show()
        self.Limonada.show()
        self.JugoEnAgua.show()
        self.JugoEnLeche.show()
        self.GranizadoFrutal.show()
        self.GranizadoCafe.show()

    def add_malteadasencilla(self):
        self.add_product_to_table('malteada sencilla')

    def add_malteadasuper(self):
        self.add_product_to_table('malteada super')

    def add_smoothie(self):
        self.add_product_to_table('smoothie')

    def add_limonada(self):
        self.add_product_to_table('limonada')

    def add_jugoenagua(self):
        self.add_product_to_table('jugo en agua')

    def add_jugoenleche(self):
        self.add_product_to_table('jugo en leche')

    def add_granizadofrutal(self):
        self.add_product_to_table('granizado frutal')

    def add_granizadocafe(self):
        self.add_product_to_table('granizado cafe')

    def show_otros(self):
        self.hide_right_buttons()
        self.BananaSplit.show()
        self.Topping.show()
        self.Empaque.show()
        self.Litro.show()
        self.MedioLitro.show()
        self.LitroPrem.show()
        self.MedioLitroPrem.show()
        self.TintoAmericano.show()
        self.Cappuccino.show()
        self.Mochaccino.show()
        self.Aromatica.show()
        self.AguaBotella.show()

    def add_bananasplit(self):
        self.add_product_to_table('banana split')

    def add_topping(self):
        self.add_product_to_table('topping')

    def add_empaque(self):
        self.add_product_to_table('empaque')

    def add_litro(self):
        self.add_product_to_table('litro')

    def add_medio_litro(self):
        self.add_product_to_table('1/2 litro')

    def add_litro_prem(self):
        self.add_product_to_table('litro prem')

    def add_medio_litro_prem(self):
        self.add_product_to_table('1/2 litro prem')

    def add_tintoamericano(self):
        self.add_product_to_table('tinto americano')

    def add_cappuccino(self):
        self.add_product_to_table('cappuccino')

    def add_mochaccino(self):
        self.add_product_to_table('mochaccino')

    def add_aromatica(self):
        self.add_product_to_table('aromatica')

    def add_agua_botella(self):
        self.add_product_to_table('agua botella')

    def open_mesa_window(self, mesa_number):
        """Abre una nueva ventana para la mesa especificada o cambia a una existente"""
        if mesa_number == 1:
            # Si es Mesa 1, volver a la ventana principal
            if Ui_page_v2.main_window:
                Ui_page_v2.main_window.activateWindow()
                Ui_page_v2.main_window.raise_()
                return
            else:
                # Si no hay ventana principal, establecer esta como principal
                Ui_page_v2.main_window = self.page_v2
                Ui_page_v2.open_windows = 1  # Inicializar contador con la ventana principal
                return
            
        # Verificar si ya existe una ventana para esta mesa
        if mesa_number in Ui_page_v2.mesa_windows:
            # Si la ventana ya existe, traerla al frente
            window = Ui_page_v2.mesa_windows[mesa_number]
            window.activateWindow()
            window.raise_()
        else:
            # Crear nueva ventana para mesas 2, 3 y 4
            if mesa_number in [2, 3, 4]:
                # Verificar que no excedamos el límite de ventanas (debe haber exactamente una por mesa)
                if mesa_number in Ui_page_v2.mesa_windows:
                    QtWidgets.QMessageBox.warning(
                        self.page_v2,
                        'Advertencia',
                        f'Ya existe una ventana para el Pedido {mesa_number}.',
                        QtWidgets.QMessageBox.Ok
                    )
                    return
                    
                self.window = QtWidgets.QWidget()
                self.ui = Ui_page_v2()
                self.ui.setupUi(self.window)
                self.ui.mesa_number = mesa_number
                self.ui.set_user_active(self.user_active.text().replace("usuario activo: ", ""))
                self.window.resize(1024, 600)
                self.window.setWindowTitle(f"Pedido {mesa_number}")
                
                # Configurar la nueva ventana y guardar referencia
                self.window.closeEvent = lambda event: self.ui.closeEvent(event)
                Ui_page_v2.mesa_windows[mesa_number] = self.window
                # Actualizar el contador de ventanas secundarias
                Ui_page_v2.open_windows = len(Ui_page_v2.mesa_windows)
                
                # Mostrar la ventana y la marca visual
                self.window.show()
                self.ui.show_pedido_marker()  # Mostrar la marca visual después de mostrar la ventana

    def open_new_window(self):
        """Vuelve a la ventana principal (Mesa 1)"""
        if Ui_page_v2.main_window:
            Ui_page_v2.main_window.activateWindow()
            Ui_page_v2.main_window.raise_()

    def close_current_window(self):
        """Abre una nueva ventana para Mesa 2"""
        self.open_mesa_window(2)

    def open_mesa3(self):
        """Abre una nueva ventana para Mesa 3"""
        self.open_mesa_window(3)

    def open_mesa4(self):
        """Abre una nueva ventana para Mesa 4"""
        self.open_mesa_window(4)

    def go_back(self):
        try:
            # Crear diálogo de advertencia
            reply = QtWidgets.QMessageBox.question(
                self.page_v2,
                'Advertencia',
                '¿Está seguro que desea volver a la ventana anterior? Se perderán los cambios no guardados.',
                QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No,
                QtWidgets.QMessageBox.No
            )
            
            if reply == QtWidgets.QMessageBox.Yes:
                # Si estamos en la entidad 1 (mesa 1)
                if getattr(self, 'mesa_number', 1) == 1:
                    if Ui_page_v2.open_windows > 1:
                        # Si hay más de una ventana abierta, no hacer nada
                        QtWidgets.QMessageBox.information(
                            self.page_v2,
                            'Información',
                            'No puede cerrar el Pedido 1 mientras existan otros pedidos abiertos.',
                            QtWidgets.QMessageBox.Ok
                        )
                        return
                    else:
                        # Solo está abierta la entidad 1, hacer transición a ventana_v1
                        from window.ventana_v1 import Ui_page_v1
                        self.window_v1 = QtWidgets.QWidget()
                        self.ui_v1 = Ui_page_v1()
                        self.ui_v1.setupUi(self.window_v1)
                        self.window_v1.resize(1024, 600)
                        self.window_v1.show()
                        self.page_v2.close()
                else:
                    # Si no es la entidad 1, cerrar la ventana normalmente
                    self.page_v2.close()
        except Exception as e:
            print(f"Error al cerrar la ventana: {e}")

    def delete_last_row(self):
        """Elimina la fila completa si se selecciona 'Producto', o establece Cant=1 si se selecciona 'Cant'"""
        selected_items = self.tableView.selectedItems()
        if selected_items:
            # Obtener la fila y columna del item seleccionado
            row = selected_items[0].row()
            column = selected_items[0].column()
            
            if column == 0:  # Si se seleccionó la columna 'Producto'
                # Eliminar la fila completa
                self.tableView.removeRow(row)
            elif column == 2:  # Si se seleccionó la columna 'Cant'
                # Establecer la cantidad a 1
                self.tableView.setItem(row, 2, QTableWidgetItem("1"))
        elif self.tableView.rowCount() > 0:
            # Si no hay selección, eliminar la última fila
            self.tableView.removeRow(self.tableView.rowCount() - 1)
        self.calculate_total()

    def calculate_total(self):
        """Calcula el total de la suma de precios por cantidades"""
        total = 0
        for row in range(self.tableView.rowCount()):
            try:
                price = float(self.tableView.item(row, 1).text())
                quantity = int(self.tableView.item(row, 2).text())
                total += price * quantity
            except (ValueError, AttributeError):
                continue
        self.label_2.setText(f"{int(total)}")

    def retranslateUi(self, page_v2):
        _translate = QtCore.QCoreApplication.translate
        page_v2.setWindowTitle(_translate("page_v2", "Pedido 1"))  # Cambiar el título aquí también
        self.user_active.setText(_translate("page_v2", "usuario activo: _____"))
        self.Helados.setText(_translate("page_v2", "HELADOS"))
        self.Cono1.setText(_translate("page_v2", "CONO 1"))
        self.Cono2.setText(_translate("page_v2", "CONO 2"))
        self.Canasta1.setText(_translate("page_v2", "CANASTA 1"))
        self.Canasta2.setText(_translate("page_v2", "CANASTA 2"))
        self.Canasta3.setText(_translate("page_v2", "CANASTA 3"))
        self.SuperCanasta.setText(_translate("page_v2", "SUPER CANASTA"))
        self.CanastaFrutal.setText(_translate("page_v2", "CANASTA FRUTAL"))
        self.CanastaAlaska.setText(_translate("page_v2", "CANASTA ALASKA"))
        self.CanastaPowIce.setText(_translate("page_v2", "CANASTA POWICE"))
        self.Paletas.setText(_translate("page_v2", "PALETAS"))
        self.Refrescante.setText(_translate("page_v2", "REFRESCANTE"))
        self.Cremosa.setText(_translate("page_v2", "CREMOSA"))
        self.SuperPaleta.setText(_translate("page_v2", "SUPER PALETA"))
        self.Obleas.setText(_translate("page_v2", "OBLEAS"))
        self.ObleaSencilla.setText(_translate("page_v2", "OBLEA SENCILLA"))
        self.SuperOblea.setText(_translate("page_v2", "SUPER OBLEA"))
        self.ObleaPowIce.setText(_translate("page_v2", "OBLEA POWICE"))
        self.Brownie.setText(_translate("page_v2", "BROWNIE"))
        self.BrownieHelado.setText(_translate("page_v2", "BROWNIE HELADO"))
        self.BrownieEspecial.setText(_translate("page_v2", "BROWNIE ESPECIAL"))
        self.BrownieNevado.setText(_translate("page_v2", "BROWNIE NEVADO"))
        self.Waffles.setText(_translate("page_v2", "WAFFLES"))
        self.Fresas.setText(_translate("page_v2", "FRESAS"))
        self.Bebidas.setText(_translate("page_v2", "BEBIDAS"))
        self.MalteadaSencilla.setText(_translate("page_v2", "MALTEADA SENCILLA"))
        self.MalteadaSuper.setText(_translate("page_v2", "MALTEADA SUPER"))
        self.Smoothie.setText(_translate("page_v2", "SMOOTHIE"))
        self.Limonada.setText(_translate("page_v2", "LIMONADA"))
        self.JugoEnAgua.setText(_translate("page_v2", "JUGO EN AGUA"))
        self.JugoEnLeche.setText(_translate("page_v2", "JUGO EN LECHE"))
        self.GranizadoFrutal.setText(_translate("page_v2", "GRANIZADO FRUTAL"))
        self.GranizadoCafe.setText(_translate("page_v2", "GRANIZADO CAFE"))
        self.Otros.setText(_translate("page_v2", "OTROS"))
        self.pushButton_2.setText(_translate("page_v2", "ATRÁS"))
        self.pushButton.setText(_translate("page_v2", "OK"))
        self.plusButton.setText(_translate("page_v2", "PEDIDO 1"))
        self.minusButton.setText(_translate("page_v2", "PEDIDO 2"))
        self.mesa3Button.setText(_translate("page_v2", "PEDIDO 3"))
        self.mesa4Button.setText(_translate("page_v2", "PEDIDO 4"))
        self.label.setText(_translate("page_v2", "TOTAL:"))
        self.label_2.setText(_translate("page_v2", "0"))
        self.pushButton_3.setText(_translate("page_v2", "BORRAR"))
        self.FresasSencillas.setText(_translate("page_v2", "FRESAS SENCILLAS"))
        self.SuperFresas.setText(_translate("page_v2", "SUPER FRESAS"))
        self.WaffleSencillo.setText(_translate("page_v2", "WAFFLE SENCILLO"))
        self.WaffleFrutal.setText(_translate("page_v2", "WAFFLE FRUTAL"))
        self.SuperWaffle.setText(_translate("page_v2", "SUPER WAFFLE"))
        self.MegaWaffles.setText(_translate("page_v2", "MEGA WAFFLES"))
        self.WaffleCosmico.setText(_translate("page_v2", "WAFFLE COSMICO"))
        self.BananaSplit.setText(_translate("page_v2", "BANANA SPLIT"))
        self.Topping.setText(_translate("page_v2", "TOPPING"))
        self.Empaque.setText(_translate("page_v2", "EMPAQUE"))
        self.Litro.setText(_translate("page_v2", "LITRO"))
        self.MedioLitro.setText(_translate("page_v2", "1/2 LITRO"))
        self.LitroPrem.setText(_translate("page_v2", "LITRO PREM"))
        self.MedioLitroPrem.setText(_translate("page_v2", "1/2 LITRO PREM"))
        self.TintoAmericano.setText(_translate("page_v2", "TINTO AMERICANO"))
        self.Cappuccino.setText(_translate("page_v2", "CAPPUCCINO"))
        self.Mochaccino.setText(_translate("page_v2", "MOCHACCINO"))
        self.Aromatica.setText(_translate("page_v2", "AROMATICA"))
        self.AguaBotella.setText(_translate("page_v2", "AGUA BOTELLA"))

    def set_user_active(self, user_name):
        """Update the user_active label with the given username"""
        self.user_active.setText(f"usuario activo: {user_name}")

    def open_v3(self):
        # Verificar si hay productos en la tabla
        if self.tableView.rowCount() == 0:
            # Mostrar mensaje de advertencia
            QtWidgets.QMessageBox.warning(
                self.page_v2,
                'Advertencia',
                'No se han agregado productos al pedido.\nDebe agregar al menos un producto para continuar.',
                QtWidgets.QMessageBox.Ok
            )
            return
            
        # Recolectar datos de productos y cantidades
        productos_venta = []
        for row in range(self.tableView.rowCount()):
            producto = self.tableView.item(row, 0).text()
            cantidad = int(self.tableView.item(row, 2).text())
            productos_venta.append((producto, cantidad))
        
        # Crear nueva ventana v3
        self.window_v3 = QtWidgets.QWidget()
        self.ui_v3 = Ui_page_v3(productos_venta)
        self.ui_v3.setupUi(self.window_v3)
        
        # Obtener el usuario activo actual y pasarlo a v3
        current_user = self.user_active.text().replace("usuario activo: ", "")
        self.ui_v3.set_user_active(current_user)
        
        # Obtener el total actual y pasarlo a v3
        total = self.label_2.text().replace("Total: $", "").replace(",", "")
        self.ui_v3.set_total(total)
        
        # Pasar la referencia de la ventana v2 actual
        self.ui_v3.set_parent_v2(self.page_v2)
        
        # Mostrar la ventana v3
        self.window_v3.resize(1024, 600)
        self.window_v3.show()
        
        # No cerrar la ventana actual (v2)

    def closeEvent(self, event):
        """Maneja el evento de cierre de la ventana"""
        try:
            # Si es la ventana principal
            if self.page_v2 == Ui_page_v2.main_window:
                # Cerrar todas las ventanas secundarias
                for window in list(Ui_page_v2.mesa_windows.values()):
                    window.close()
                Ui_page_v2.mesa_windows.clear()
                Ui_page_v2.main_window = None
                Ui_page_v2.open_windows = 0
            else:
                # Si es una ventana secundaria
                if hasattr(self, 'mesa_number') and self.mesa_number in Ui_page_v2.mesa_windows:
                    del Ui_page_v2.mesa_windows[self.mesa_number]
                Ui_page_v2.open_windows = len(Ui_page_v2.mesa_windows)
            
            event.accept()
        except Exception as e:
            print(f"Error en closeEvent: {e}")
            event.accept()

    def show_pedido_marker(self):
        # Elimina la marca anterior si existe
        if hasattr(self, 'pedido_marker') and self.pedido_marker:
            self.pedido_marker.deleteLater()
            self.pedido_marker = None
        # Mapeo de número de pedido a nombre de botón
        pedido_buttons = {
            1: 'plusButton',
            2: 'minusButton',
            3: 'mesa3Button',
            4: 'mesa4Button',
        }
        if self.mesa_number in pedido_buttons:
            boton_nombre = pedido_buttons[self.mesa_number]
            boton = getattr(self, boton_nombre, None)
            if boton:
                # Obtener posición absoluta del botón respecto a la ventana
                pos = boton.pos()
                x = pos.x() + (boton.width() - 30) // 2
                y = pos.y() - 32
                self.pedido_marker = QtWidgets.QLabel(self.page_v2)
                self.pedido_marker.setText('★')
                self.pedido_marker.setAlignment(QtCore.Qt.AlignCenter)
                self.pedido_marker.setStyleSheet('''
                    QLabel {
                        color: gold;
                        font-size: 28px;
                        background: transparent;
                    }
                ''')
                self.pedido_marker.setFixedSize(30, 30)
                self.pedido_marker.move(x, y)
                self.pedido_marker.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    page_v2 = QtWidgets.QDialog()
    ui = Ui_page_v2()
    ui.setupUi(page_v2)
    page_v2.show()
    sys.exit(app.exec_())

