# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pow_ice_page_v1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3  # Import SQLite for database interaction
from window.ventana_v2 import Ui_page_v2  # Import ventana_v2
from datetime import datetime  # Import datetime para manejar fechas


class Ui_page_v1(object):
    def setupUi(self, page_v1):
        self.page_v1 = page_v1  # Guardar referencia a la ventana
        page_v1.setObjectName("page_v1")
        page_v1.resize(400, 300)
        page_v1.setWindowFlags(QtCore.Qt.Window | QtCore.Qt.CustomizeWindowHint | QtCore.Qt.WindowTitleHint)  # Disable close button

        # Crear layout vertical principal
        main_layout = QtWidgets.QVBoxLayout(page_v1)
        main_layout.setContentsMargins(20, 20, 20, 20)
        main_layout.setSpacing(15)

        # Label para el título
        self.label = QtWidgets.QLabel(page_v1)
        self.label.setObjectName("label")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        main_layout.addWidget(self.label)

        # LineEdit para el usuario
        self.username_in = QtWidgets.QLineEdit(page_v1)
        self.username_in.setObjectName("username_in")
        self.username_in.setFixedWidth(200)
        self.username_in.setAlignment(QtCore.Qt.AlignCenter)
        main_layout.addWidget(self.username_in, alignment=QtCore.Qt.AlignCenter)

        # Label para mensajes de validación
        self.user_ivalid = QtWidgets.QLabel(page_v1)
        self.user_ivalid.setObjectName("user_ivalid")
        self.user_ivalid.setAlignment(QtCore.Qt.AlignCenter)
        main_layout.addWidget(self.user_ivalid)

        # Layout horizontal para los botones OK y Atrás
        button_layout = QtWidgets.QHBoxLayout()
        button_layout.setSpacing(0)  # Sin espaciado entre botones
        button_layout.setContentsMargins(0, 0, 0, 0)  # Sin márgenes

        # Botón OK
        self.pushButton = QtWidgets.QPushButton(page_v1)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setFixedWidth(95)  # Reducido ligeramente el ancho
        self.pushButton.clicked.connect(self.validate_user)
        button_layout.addWidget(self.pushButton)

        # Botón Atrás
        self.pushButton_2 = QtWidgets.QPushButton(page_v1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setFixedWidth(95)  # Reducido ligeramente el ancho
        self.pushButton_2.clicked.connect(self.go_back)
        button_layout.addWidget(self.pushButton_2)

        # Agregar el layout de botones al layout principal
        main_layout.addLayout(button_layout)

        # Botón Venta del día
        self.venta_dia_button = QtWidgets.QPushButton(page_v1)
        self.venta_dia_button.setObjectName("venta_dia_button")
        self.venta_dia_button.setFixedWidth(200)
        self.venta_dia_button.clicked.connect(self.show_ventas_dia)  # Conectar el botón
        main_layout.addWidget(self.venta_dia_button, alignment=QtCore.Qt.AlignCenter)

        # Agregar espaciador flexible al final
        main_layout.addStretch()

        self.user_name = None  # Store the user's name

        self.retranslateUi(page_v1)
        QtCore.QMetaObject.connectSlotsByName(page_v1)

    def go_back(self):
        try:
            # Obtener la ventana principal
            main_window = None
            for widget in QtWidgets.QApplication.topLevelWidgets():
                if isinstance(widget, QtWidgets.QMainWindow):
                    main_window = widget
                    break
            
            if main_window:
                main_window.show()
                self.page_v1.close()
            else:
                print("No se encontró la ventana principal")
        except Exception as e:
            print(f"Error al volver a la ventana principal: {e}")

    def validate_user(self):
        input_text = self.username_in.text()
        if not input_text.isdigit():  # Check if input is numeric
            self.user_ivalid.setText("Usuario incorrecto")
            return

        user_id = int(input_text)
        try:
            # Connect to the database
            connection = sqlite3.connect("/home/andres/Documentos/app_heladeria/databases/Pow_Ice")
            cursor = connection.cursor()

            # Query to check if the ID exists and fetch the name
            cursor.execute("SELECT nombre FROM usuarios WHERE id = ?", (user_id,))
            result = cursor.fetchone()

            if result:
                self.user_name = result[0]  # Store the user's name
                self.user_ivalid.setText("Usuario correcto")
                self.open_ventana_v2()  # Open ventana_v2 if user is valid
            else:
                self.user_ivalid.setText("Usuario incorrecto")

        except sqlite3.Error as e:
            self.user_ivalid.setText("Error de BD")
            print(f"Database error: {e}")
        finally:
            if connection:
                connection.close()

    def open_ventana_v2(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_page_v2()
        self.ui.setupUi(self.window)
        self.ui.set_user_active(self.user_name)  # Pass the user's name to ventana_v2
        self.window.resize(1024, 600)  # Set resolution to 1024x600
        self.window.show()
        QtWidgets.QApplication.instance().activeWindow().hide()  # Hide the current window

    def show_ventas_dia(self):
        try:
            # Crear ventana de diálogo
            dialog = QtWidgets.QDialog(self.page_v1)
            dialog.setWindowTitle("Ventas del Día")
            dialog.resize(800, 400)

            # Crear layout vertical para la ventana
            layout = QtWidgets.QVBoxLayout(dialog)

            # Crear tabla
            table = QtWidgets.QTableWidget()
            table.setColumnCount(4)
            table.setHorizontalHeaderLabels(["Producto", "Cantidad", "Precio Unitario", "Total"])
            table.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)

            # Conectar a la base de datos
            conn = sqlite3.connect('/home/andres/Documentos/app_heladeria/databases/Pow_Ice')
            cursor = conn.cursor()

            # Obtener la fecha actual
            fecha_actual = datetime.now().strftime('%Y-%m-%d')

            # Consultar ventas del día
            cursor.execute("""
                SELECT p.product, SUM(v.cant) as cantidad, p.price, SUM(v.cant * p.price) as total
                FROM ventas v
                JOIN products p ON v.id_product = p.id
                WHERE date(v.fecha) = ?
                GROUP BY p.id, p.product, p.price
                ORDER BY p.product
            """, (fecha_actual,))

            # Llenar la tabla con los resultados
            for row, data in enumerate(cursor.fetchall()):
                table.insertRow(row)
                for col, value in enumerate(data):
                    item = QtWidgets.QTableWidgetItem(str(value))
                    if col in [1, 2, 3]:  # Alinear números a la derecha
                        item.setTextAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)
                    table.setItem(row, col, item)

            # Calcular total del día
            cursor.execute("""
                SELECT SUM(v.cant * p.price) as total_dia
                FROM ventas v
                JOIN products p ON v.id_product = p.id
                WHERE date(v.fecha) = ?
            """, (fecha_actual,))
            total_dia = cursor.fetchone()[0] or 0

            # Agregar la tabla al layout
            layout.addWidget(table)

            # Agregar label con el total
            total_label = QtWidgets.QLabel(f"Total del día: ${total_dia:,.0f}")
            total_label.setAlignment(QtCore.Qt.AlignRight)
            layout.addWidget(total_label)

            # Botón para cerrar
            close_button = QtWidgets.QPushButton("Cerrar")
            close_button.clicked.connect(dialog.close)
            layout.addWidget(close_button, alignment=QtCore.Qt.AlignCenter)

            conn.close()
            dialog.exec_()

        except sqlite3.Error as e:
            QtWidgets.QMessageBox.critical(self.page_v1, "Error", f"Error de base de datos: {str(e)}")
        except Exception as e:
            QtWidgets.QMessageBox.critical(self.page_v1, "Error", f"Error inesperado: {str(e)}")

    def retranslateUi(self, page_v1):
        _translate = QtCore.QCoreApplication.translate
        page_v1.setWindowTitle(_translate("page_v1", "page_v1"))
        self.label.setText(_translate("page_v1", "Ingrese su Usuario"))
        self.pushButton_2.setText(_translate("page_v1", "Atrás"))
        self.pushButton.setText(_translate("page_v1", "OK"))
        self.venta_dia_button.setText(_translate("page_v1", "Venta del día"))
