# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pow_ice_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from window.ventana_v1 import Ui_page_v1  # Import the ventana_v1 script


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(1024, 600)
        main.setWindowFlags(QtCore.Qt.Window | QtCore.Qt.CustomizeWindowHint | QtCore.Qt.WindowTitleHint)  # Disable close button
        self.ventas = QtWidgets.QPushButton(main)
        self.ventas.setGeometry(QtCore.QRect(411, 150, 202, 48))  # Centered horizontally
        self.ventas.setObjectName("ventas")
        self.ventas.clicked.connect(self.open_ventas)  # Connect button to function
        self.pushButton_2 = QtWidgets.QPushButton(main)
        self.pushButton_2.setGeometry(QtCore.QRect(391, 250, 242, 48))  # Centered horizontally
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(main)
        self.pushButton_3.setGeometry(QtCore.QRect(421, 350, 182, 48))  # Centered horizontally
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "Pow Ice main"))
        self.ventas.setText(_translate("main", "Iniciar Ventas"))
        self.pushButton_2.setText(_translate("main", "ingresar compas"))
        self.pushButton_3.setText(_translate("main", "Administrar"))

    def open_ventas(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_page_v1()
        self.ui.setupUi(self.window)
        self.window.resize(1024, 600)  # Set resolution to 1024x600
        self.window.show()
        QtWidgets.QApplication.instance().activeWindow().hide()  # Hide the current window
