# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pow_ice_page_v3.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import datetime


class Ui_page_v3(object):
    def setupUi(self, page_v3):
        self.page_v3 = page_v3  # Guardar referencia a la ventana principal
        page_v3.setObjectName("page_v3")
        page_v3.resize(1024, 600)
        page_v3.setWindowFlags(QtCore.Qt.Window | QtCore.Qt.CustomizeWindowHint | QtCore.Qt.WindowTitleHint)  # Disable close button
        
        self.user_active = QtWidgets.QLabel(page_v3)
        self.user_active.setGeometry(QtCore.QRect(150, 0, 300, 20))
        self.user_active.setObjectName("user_active")
        
        # Agregar label para fecha y hora
        self.datetime_label = QtWidgets.QLabel(page_v3)
        self.datetime_label.setGeometry(QtCore.QRect(150, 20, 300, 20))
        self.datetime_label.setObjectName("datetime_label")
        
        # Agregar label para el total
        self.total_label = QtWidgets.QLabel(page_v3)
        self.total_label.setGeometry(QtCore.QRect(150, 40, 300, 20))
        self.total_label.setObjectName("total_label")
        
        # Timer para actualizar la fecha y hora
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.update_datetime)
        self.timer.start(1000)  # Actualizar cada segundo
        
        self.label = QtWidgets.QLabel(page_v3)
        self.label.setGeometry(QtCore.QRect(160, 70, 111, 22))
        self.label.setObjectName("label")
        
        self.radioButton = QtWidgets.QRadioButton(page_v3)
        self.radioButton.setGeometry(QtCore.QRect(160, 100, 114, 28))
        self.radioButton.setObjectName("radioButton")
        
        self.radioButton_2 = QtWidgets.QRadioButton(page_v3)
        self.radioButton_2.setGeometry(QtCore.QRect(160, 130, 114, 28))
        self.radioButton_2.setObjectName("radioButton_2")
        
        self.radioButton_3 = QtWidgets.QRadioButton(page_v3)
        self.radioButton_3.setGeometry(QtCore.QRect(160, 160, 114, 28))
        self.radioButton_3.setObjectName("radioButton_3")
        
        self.radioButton_4 = QtWidgets.QRadioButton(page_v3)
        self.radioButton_4.setGeometry(QtCore.QRect(160, 190, 114, 28))
        self.radioButton_4.setObjectName("radioButton_4")
        
        self.pushButton = QtWidgets.QPushButton(page_v3)
        self.pushButton.setGeometry(QtCore.QRect(310, 240, 91, 30))
        self.pushButton.setObjectName("pushButton")
        
        self.pushButton_2 = QtWidgets.QPushButton(page_v3)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 240, 91, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.go_back)

        self.retranslateUi(page_v3)
        QtCore.QMetaObject.connectSlotsByName(page_v3)

    def go_back(self):
        try:
            # Simplemente cerrar la ventana actual
            self.page_v3.close()
        except Exception as e:
            print(f"Error al cerrar la ventana: {e}")

    def set_user_active(self, user_name):
        """Update the user_active label with the given username"""
        self.user_active.setText(f"usuario activo: {user_name}")

    def update_datetime(self):
        """Actualiza la fecha y hora en el label"""
        current_datetime = datetime.now().strftime("%d/%m/%Y %H:%M:%S")
        self.datetime_label.setText(f"Fecha y hora: {current_datetime}")

    def set_total(self, total):
        """Actualiza el label del total"""
        self.total_label.setText(f"Total: ${total}")

    def retranslateUi(self, page_v3):
        _translate = QtCore.QCoreApplication.translate
        page_v3.setWindowTitle(_translate("page_v3", "page_v3"))
        self.user_active.setText(_translate("page_v3", "usuario activo: _____"))
        self.datetime_label.setText(_translate("page_v3", "Fecha y hora: "))
        self.total_label.setText(_translate("page_v3", "Total: $0"))
        self.label.setText(_translate("page_v3", "Medio De Pago"))
        self.radioButton.setText(_translate("page_v3", "Efectivo"))
        self.radioButton_2.setText(_translate("page_v3", "Daviplata"))
        self.radioButton_3.setText(_translate("page_v3", "Pago Mixto"))
        self.radioButton_4.setText(_translate("page_v3", "Nequi"))
        self.pushButton_2.setText(_translate("page_v3", "Atrás"))
        self.pushButton.setText(_translate("page_v3", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    page_v3 = QtWidgets.QDialog()
    ui = Ui_page_v3()
    ui.setupUi(page_v3)
    page_v3.show()
    sys.exit(app.exec_())
