# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pow_ice_page_v3.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import datetime
import sqlite3
from window.ventana_vfinal import Ui_page_vfinal

try:
    import RPi.GPIO as GPIO
    IS_RPI = True
except (ImportError, RuntimeError):
    IS_RPI = False
    # Mock GPIO para desarrollo en PC
    class MockGPIO:
        BCM = OUT = HIGH = LOW = None
        def setmode(self, *args, **kwargs): pass
        def setup(self, *args, **kwargs): pass
        def output(self, *args, **kwargs): pass
    GPIO = MockGPIO()



#import RPi.GPIO as GPIO  # Importar GPIO para Raspberry Pi

# Configurar GPIO
GPIO.setmode(GPIO.BCM)
GPIO.setup(24, GPIO.OUT)  # Configurar pin 24 como salida
GPIO.output(24, GPIO.HIGH)  # Inicializar en estado alto


class Ui_page_v3(object):
    def __init__(self, productos_venta=None):
        self.productos_venta = productos_venta or []
        self.user_active = None
        self.total = None
        self.parent_v2 = None

    def setupUi(self, page_v3):
        self.page_v3 = page_v3  # Guardar referencia a la ventana principal
        page_v3.setObjectName("page_v3")
        page_v3.resize(1024, 600)
        page_v3.setWindowFlags(QtCore.Qt.Window | QtCore.Qt.CustomizeWindowHint | QtCore.Qt.WindowTitleHint)  # Disable close button
        page_v3.setWindowTitle("Pedido 1")  # Establecer título de la ventana principal

        # Crear frame de fondo
        self.background_frame = QtWidgets.QFrame(page_v3)
        self.background_frame.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.background_frame.setStyleSheet("background-color: #E6F3FF;")  # Mismo color que el fondo
        self.background_frame.lower()  # Enviar al fondo

        # Establecer el color de fondo de la ventana (tono azul claro)
        page_v3.setStyleSheet("""
            QWidget {
                background-color: #E6F3FF;  /* Azul pastel claro */
            }
            QPushButton {
                background-color: #4A90E2;  /* Azul medio */
                border: 3px solid #2C5282;  /* Azul oscuro */
                border-radius: 15px;
                color: white;  /* Texto blanco para mejor contraste */
                padding: 5px;
                font-size: 28px;
            }
            QPushButton:hover {
                background-color: #2C5282;  /* Azul oscuro al pasar el mouse */
                color: white;
            }
            QLabel {
                color: #1A365D;  /* Azul muy oscuro para el texto */
                font-size: 28px;
            }
            QTableWidget {
                background-color: white;
                border: 3px solid #4A90E2;
                border-radius: 10px;
                gridline-color: #E6F3FF;
            }
            QTableWidget::item {
                padding: 5px;
                font-size: 28px;
            }
            QTableWidget::item:selected {
                background-color: #4A90E2;
                color: white;
            }
            QHeaderView::section {
                background-color: #4A90E2;
                color: white;
                padding: 5px;
                border: 1px solid #2C5282;
                font-size: 28px;
            }
            QLineEdit {
                background-color: white;
                border: 2px solid #4A90E2;
                border-radius: 10px;
                padding: 5px;
                color: #1A365D;
                font-size: 28px;
            }
            QLineEdit:focus {
                border: 2px solid #2C5282;
                background-color: #F0F7FF;
            }
            QRadioButton {
                color: #1A365D;
                font-size: 28px;
            }
            QRadioButton::indicator {
                width: 25px;
                height: 25px;
            }
            QRadioButton::indicator:unchecked {
                border: 2px solid #4A90E2;
                background-color: white;
                border-radius: 10px;
            }
            QRadioButton::indicator:checked {
                border: 2px solid #2C5282;
                background-color: #4A90E2;
                border-radius: 10px;
            }
        """)
        
        # Label para usuario activo
        self.user_active = QtWidgets.QLabel(page_v3)
        self.user_active.setGeometry(QtCore.QRect(20, 20, 400, 40))  # Aumentado el ancho para el usuario
        self.user_active.setObjectName("user_active")
        font = QtGui.QFont()
        font.setPointSize(12)  # Aumentado tamaño de fuente
        self.user_active.setFont(font)
        
        # Label para fecha y hora
        self.datetime_label = QtWidgets.QLabel(page_v3)
        self.datetime_label.setGeometry(QtCore.QRect(440, 20, 300, 40))  # Movido más a la derecha
        self.datetime_label.setObjectName("datetime_label")
        self.datetime_label.setFont(font)
        
        # Label para total
        self.total_label = QtWidgets.QLabel(page_v3)
        self.total_label.setGeometry(QtCore.QRect(760, 20, 300, 40))  # Movido más a la derecha
        self.total_label.setObjectName("total_label")
        self.total_label.setFont(font)
        
        # Label para medio de pago
        self.label = QtWidgets.QLabel(page_v3)
        self.label.setGeometry(QtCore.QRect(20, 80, 200, 40))  # Ajustada la posición Y
        self.label.setObjectName("label")
        font.setPointSize(14)  # Aumentado tamaño de fuente
        self.label.setFont(font)
        
        # Timer para actualizar la fecha y hora
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.update_datetime)
        self.timer.start(60000)  # Actualizar cada minuto (60000 ms)
        
        # Actualizar la fecha y hora inmediatamente
        current_datetime = datetime.now().strftime("%d/%m/%Y %H:%M")
        self.datetime_label.setText(f"Fecha y hora: {current_datetime}")
        
        # Radio buttons para métodos de pago
        self.radioButton = QtWidgets.QRadioButton(page_v3)
        self.radioButton.setGeometry(QtCore.QRect(20, 140, 200, 40))  # Aumentado tamaño y posición
        self.radioButton.setObjectName("radioButton")
        self.radioButton.setFont(font)
        self.radioButton.toggled.connect(self.on_efectivo_toggled)
        
        self.radioButton_2 = QtWidgets.QRadioButton(page_v3)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 190, 200, 40))  # Aumentado tamaño y posición
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_2.setFont(font)
        self.radioButton_2.toggled.connect(self.on_daviplata_toggled)
        
        self.radioButton_3 = QtWidgets.QRadioButton(page_v3)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 240, 200, 40))  # Aumentado tamaño y posición
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_3.setFont(font)
        self.radioButton_3.toggled.connect(self.on_pago_mixto_toggled)
        
        self.radioButton_4 = QtWidgets.QRadioButton(page_v3)
        self.radioButton_4.setGeometry(QtCore.QRect(20, 290, 200, 40))  # Aumentado tamaño y posición
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_4.setFont(font)
        self.radioButton_4.toggled.connect(self.on_nequi_toggled)
        
        # Labels y campos para efectivo
        self.recibido_label = QtWidgets.QLabel(page_v3)
        self.recibido_label.setGeometry(QtCore.QRect(300, 140, 200, 40))  # Aumentado tamaño y posición
        self.recibido_label.setObjectName("recibido_label")
        self.recibido_label.setFont(font)
        self.recibido_label.hide()
        
        self.recibido_input = QtWidgets.QLineEdit(page_v3)
        self.recibido_input.setGeometry(QtCore.QRect(300, 190, 200, 40))  # Aumentado tamaño y posición
        self.recibido_input.setObjectName("recibido_input")
        self.recibido_input.setFont(font)
        self.recibido_input.setValidator(QtGui.QIntValidator())
        self.recibido_input.hide()
        
        # Radio buttons para pago mixto
        self.radioButton_mixto_nequi = QtWidgets.QRadioButton(page_v3)
        self.radioButton_mixto_nequi.setGeometry(QtCore.QRect(300, 140, 200, 40))  # Aumentado tamaño y posición
        self.radioButton_mixto_nequi.setObjectName("radioButton_mixto_nequi")
        self.radioButton_mixto_nequi.setFont(font)
        self.radioButton_mixto_nequi.hide()
        
        self.radioButton_mixto_daviplata = QtWidgets.QRadioButton(page_v3)
        self.radioButton_mixto_daviplata.setGeometry(QtCore.QRect(300, 190, 200, 40))  # Aumentado tamaño y posición
        self.radioButton_mixto_daviplata.setObjectName("radioButton_mixto_daviplata")
        self.radioButton_mixto_daviplata.setFont(font)
        self.radioButton_mixto_daviplata.hide()
        
        # Labels y campos para pago mixto
        self.efectivo_mixto_label = QtWidgets.QLabel(page_v3)
        self.efectivo_mixto_label.setGeometry(QtCore.QRect(300, 240, 200, 40))  # Aumentado tamaño y posición
        self.efectivo_mixto_label.setObjectName("efectivo_mixto_label")
        self.efectivo_mixto_label.setFont(font)
        self.efectivo_mixto_label.hide()
        
        self.efectivo_mixto_input = QtWidgets.QLineEdit(page_v3)
        self.efectivo_mixto_input.setGeometry(QtCore.QRect(300, 290, 200, 40))  # Aumentado tamaño y posición
        self.efectivo_mixto_input.setObjectName("efectivo_mixto_input")
        self.efectivo_mixto_input.setFont(font)
        self.efectivo_mixto_input.setValidator(QtGui.QIntValidator())
        self.efectivo_mixto_input.hide()
        self.efectivo_mixto_input.textChanged.connect(lambda: self.update_difference(self.efectivo_mixto_input, self.transferencia_mixto_input))
        
        self.transferencia_mixto_label = QtWidgets.QLabel(page_v3)
        self.transferencia_mixto_label.setGeometry(QtCore.QRect(520, 240, 200, 40))  # Aumentado tamaño y posición
        self.transferencia_mixto_label.setObjectName("transferencia_mixto_label")
        self.transferencia_mixto_label.setFont(font)
        self.transferencia_mixto_label.hide()
        
        self.transferencia_mixto_input = QtWidgets.QLineEdit(page_v3)
        self.transferencia_mixto_input.setGeometry(QtCore.QRect(520, 290, 200, 40))  # Aumentado tamaño y posición
        self.transferencia_mixto_input.setObjectName("transference_mixto_input")
        self.transferencia_mixto_input.setFont(font)
        self.transferencia_mixto_input.setValidator(QtGui.QIntValidator())
        self.transferencia_mixto_input.hide()
        self.transferencia_mixto_input.textChanged.connect(lambda: self.update_difference(self.transferencia_mixto_input, self.efectivo_mixto_input))
        
        # Labels para diferencias
        self.diferencia_efectivo_label = QtWidgets.QLabel(page_v3)
        self.diferencia_efectivo_label.setGeometry(QtCore.QRect(300, 340, 200, 40))  # Aumentado tamaño y posición
        self.diferencia_efectivo_label.setObjectName("diferencia_efectivo_label")
        self.diferencia_efectivo_label.setFont(font)
        self.diferencia_efectivo_label.hide()
        
        self.diferencia_transferencia_label = QtWidgets.QLabel(page_v3)
        self.diferencia_transferencia_label.setGeometry(QtCore.QRect(520, 340, 200, 40))  # Aumentado tamaño y posición
        self.diferencia_transferencia_label.setObjectName("diferencia_transferencia_label")
        self.diferencia_transferencia_label.setFont(font)
        self.diferencia_transferencia_label.hide()
        
        # Botones de control
        self.pushButton_2 = QtWidgets.QPushButton(page_v3)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 400, 200, 50))  # Aumentado tamaño y posición
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setFont(font)
        self.pushButton_2.clicked.connect(self.go_back)
        
        self.pushButton = QtWidgets.QPushButton(page_v3)
        self.pushButton.setGeometry(QtCore.QRect(240, 400, 200, 50))  # Aumentado tamaño y posición
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setFont(font)
        self.pushButton.clicked.connect(self.on_ok_clicked)

        self.retranslateUi(page_v3)
        QtCore.QMetaObject.connectSlotsByName(page_v3)

    def go_back(self):
        try:
            # Simplemente cerrar la ventana actual
            self.page_v3.close()
        except Exception as e:
            print(f"Error al cerrar la ventana: {e}")

    def set_user_active(self, user_name):
        """Update the user_active label with the given username"""
        self.user_active.setText(f"usuario activo: {user_name}")

    def update_datetime(self):
        """Actualiza la fecha y hora en el label"""
        try:
            current_datetime = datetime.now().strftime("%d/%m/%Y %H:%M")
            self.datetime_label.setText(f"Fecha y hora: {current_datetime}")
        except Exception as e:
            print(f"Error al actualizar la fecha y hora: {e}")
            self.datetime_label.setText("Fecha y hora: --/--/---- --:--")

    def set_total(self, total):
        """Actualiza el label del total"""
        self.total_label.setText(f"Total: ${total}")

    def clear_right_side(self):
        """Limpia todos los elementos del lado derecho"""
        self.recibido_label.hide()
        self.recibido_input.hide()
        self.recibido_input.clear()
        self.radioButton_mixto_nequi.hide()
        self.radioButton_mixto_daviplata.hide()
        self.efectivo_mixto_label.hide()
        self.efectivo_mixto_input.hide()
        self.efectivo_mixto_input.clear()
        self.transferencia_mixto_label.hide()
        self.transferencia_mixto_input.hide()
        self.transferencia_mixto_input.clear()
        self.diferencia_efectivo_label.hide()
        self.diferencia_transferencia_label.hide()

    def on_efectivo_toggled(self, checked):
        """Maneja el evento cuando se selecciona/deselecciona el radio button de efectivo"""
        self.clear_right_side()  # Limpiar todo primero
        if checked:
            self.recibido_label.show()
            self.recibido_input.show()

    def on_daviplata_toggled(self, checked):
        """Maneja el evento cuando se selecciona/deselecciona el radio button de daviplata"""
        self.clear_right_side()  # Limpiar todo primero

    def on_pago_mixto_toggled(self, checked):
        """Maneja el evento cuando se selecciona/deselecciona el radio button de pago mixto"""
        self.clear_right_side()  # Limpiar todo primero
        if checked:
            self.radioButton_mixto_nequi.show()
            self.radioButton_mixto_daviplata.show()
            self.efectivo_mixto_label.show()
            self.efectivo_mixto_input.show()
            self.transferencia_mixto_label.show()
            self.transferencia_mixto_input.show()
            self.diferencia_efectivo_label.show()
            self.diferencia_transferencia_label.show()

    def on_nequi_toggled(self, checked):
        """Maneja el evento cuando se selecciona/deselecciona el radio button de nequi"""
        self.clear_right_side()  # Limpiar todo primero

    def set_parent_v2(self, parent_v2):
        """Guarda la referencia a la ventana v2 padre"""
        self.parent_v2 = parent_v2

    def on_ok_clicked(self):
        try:
            # Verificar si se seleccionó un método de pago
            payment_method = None
            received_amount = None  # Variable para almacenar el valor recibido
            
            if self.radioButton.isChecked():
                payment_method = "efectivo"
                # Verificar si se ingresó el valor recibido
                if not self.recibido_input.text():
                    QtWidgets.QMessageBox.warning(self.page_v3, "Advertencia", "Por favor ingrese el valor recibido")
                    return
                received_amount = self.recibido_input.text()
                # Verificar que el valor recibido no sea menor al total
                total_value = int(self.total_label.text().replace("Total: $", "").replace(",", ""))
                if int(received_amount) < total_value:
                    QtWidgets.QMessageBox.warning(self.page_v3, "Advertencia", 
                        f"El valor recibido (${received_amount}) no puede ser menor al total (${total_value})")
                    return
            elif self.radioButton_2.isChecked():
                payment_method = "daviplata"
            elif self.radioButton_3.isChecked():
                payment_method = "pago mixto"
                # Verificar si se ingresó el valor en efectivo
                if not self.efectivo_mixto_input.text():
                    QtWidgets.QMessageBox.warning(self.page_v3, "Advertencia", "Por favor ingrese el valor en efectivo")
                    return
                # Verificar si se seleccionó el método de transferencia
                if not (self.radioButton_mixto_nequi.isChecked() or self.radioButton_mixto_daviplata.isChecked()):
                    QtWidgets.QMessageBox.warning(self.page_v3, "Advertencia", "Por favor seleccione el método de transferencia")
                    return
                # Obtener el valor en efectivo para el pago mixto
                efectivo_value = int(self.efectivo_mixto_input.text())
                transferencia_value = int(self.transferencia_mixto_input.text())
                total_value = int(self.total_label.text().replace("Total: $", "").replace(",", ""))
                
                # Verificar que la suma sea igual al total
                if efectivo_value + transferencia_value != total_value:
                    QtWidgets.QMessageBox.warning(self.page_v3, "Advertencia", 
                        f"La suma del efectivo (${efectivo_value}) y la transferencia (${transferencia_value}) debe ser igual al total (${total_value})")
                    return
                
                received_amount = str(efectivo_value)
            elif self.radioButton_4.isChecked():
                payment_method = "nequi"
            
            if not payment_method:
                QtWidgets.QMessageBox.warning(self.page_v3, "Advertencia", "Por favor seleccione un método de pago")
                return
            
            # Obtener el usuario activo
            current_user = self.user_active.text().replace("usuario activo: ", "").strip()
            
            # Obtener el total
            total = self.total_label.text().replace("Total: $", "").replace(",", "")
            
            # Conectar a la base de datos
            conn = sqlite3.connect('/home/andres/Documentos/databases_heladeria/Pow_Ice')
            cursor = conn.cursor()
            
            # Obtener el ID del usuario (case insensitive)
            cursor.execute("SELECT id FROM usuarios WHERE nombre = ?", (current_user,))
            user_result = cursor.fetchone()
            if not user_result:
                QtWidgets.QMessageBox.critical(self.page_v3, "Error", f"No se encontró el usuario '{current_user}' en la base de datos")
                conn.close()
                return
            user_id = user_result[0]
            
            # Obtener el ID del tipo de pago
            if payment_method == "pago mixto":
                # Determinar el tipo específico de pago mixto
                if self.radioButton_mixto_nequi.isChecked():
                    payment_method = "mixto nequi"
                elif self.radioButton_mixto_daviplata.isChecked():
                    payment_method = "mixto daviplata"
            
            cursor.execute("SELECT id FROM tipo_de_pago WHERE tipo = ?", (payment_method,))
            payment_result = cursor.fetchone()
            if not payment_result:
                QtWidgets.QMessageBox.critical(self.page_v3, "Error", "No se encontró el tipo de pago en la base de datos")
                conn.close()
                return
            payment_type_id = payment_result[0]
            
            # Obtener fecha y hora del datetime_label
            datetime_str = self.datetime_label.text().replace("Fecha y hora: ", "")
            date_str, time_str = datetime_str.split(" ")
            
            # Convertir fecha al formato SQL (YYYY-MM-DD)
            date_parts = date_str.split("/")
            sql_date = f"{date_parts[2]}-{date_parts[1]}-{date_parts[0]}"
            
            # Obtener los productos de la venta desde la ventana v2
            if not hasattr(self, 'parent_v2') or not self.parent_v2:
                QtWidgets.QMessageBox.critical(self.page_v3, "Error", "No se pudo encontrar la ventana de productos")
                conn.close()
                return
                
            # Obtener la interfaz de usuario de la ventana v2
            v2_ui = None
            for child in self.parent_v2.children():
                if isinstance(child, QtWidgets.QTableWidget):
                    v2_ui = child
                    break
            
            if not v2_ui:
                QtWidgets.QMessageBox.critical(self.page_v3, "Error", "No se pudo encontrar la tabla de productos")
                conn.close()
                return
                
            # Obtener los productos de la venta
            productos_venta = []
            for row in range(v2_ui.rowCount()):
                product_name = v2_ui.item(row, 0).text()
                quantity = int(v2_ui.item(row, 2).text())
                
                # Obtener el ID del producto
                cursor.execute("SELECT id FROM products WHERE product = ?", (product_name.lower(),))
                product_result = cursor.fetchone()
                if not product_result:
                    QtWidgets.QMessageBox.critical(self.page_v3, "Error", f"No se encontró el producto {product_name} en la base de datos")
                    conn.close()
                    return
                product_id = product_result[0]
                
                productos_venta.append((product_id, quantity))
            
            # Guardar cada producto en la tabla de ventas
            # Calcular la diferencia por producto si es pago mixto
            diferencia_por_producto = None
            if payment_method == "mixto nequi" or payment_method == "mixto daviplata":
                efectivo_value = int(self.efectivo_mixto_input.text())
                diferencia_por_producto = efectivo_value // len(productos_venta)

            for product_id, quantity in productos_venta:
                # Determinar el valor de la diferencia
                diferencia = diferencia_por_producto if (payment_method == "mixto nequi" or payment_method == "mixto daviplata") else None
                
                cursor.execute("""
                    INSERT INTO ventas (
                        fecha, 
                        hora, 
                        id_usuario, 
                        id_product, 
                        id_tipo, 
                        diferencia,
                        cant
                    )
                    VALUES (?, ?, ?, ?, ?, ?, ?)
                """, (
                    sql_date, 
                    time_str, 
                    user_id, 
                    product_id, 
                    payment_type_id, 
                    diferencia,
                    quantity
                ))
            
            # Guardar los cambios
            conn.commit()
            conn.close()
            
            # Activar GPIO pin 24 para caja registradora (solo en efectivo o mixto)
            if payment_method == "efectivo" or payment_method.startswith("mixto"):
                try:
                    GPIO.output(24, GPIO.LOW)  # Activar el relay
                    print("GPIO pin 24 activado para caja registradora")
                    # Mantener activo por 500ms
                    QtCore.QTimer.singleShot(100, lambda: GPIO.output(24, GPIO.HIGH))
                except Exception as e:
                    print(f"Error al activar GPIO: {e}")
            
            # Crear y mostrar la ventana final
            self.window_vfinal = QtWidgets.QWidget()
            self.ui_vfinal = Ui_page_vfinal()
            self.ui_vfinal.setupUi(self.window_vfinal)
            
            # Configurar la ventana final
            self.ui_vfinal.set_user_active(current_user)
            self.ui_vfinal.set_total(total)
            self.ui_vfinal.set_payment_method(payment_method)
            
            # Si hay un valor recibido, pasarlo a la ventana final
            if received_amount:
                self.ui_vfinal.set_total(total, received_amount)
            
            # Pasar la referencia de la ventana v2 original
            self.ui_vfinal.set_parent_v2(self.parent_v2)
            
            # Mostrar la ventana final
            self.window_vfinal.resize(1024, 600)
            self.window_vfinal.show()
            
            # Cerrar la ventana actual
            self.page_v3.close()
            
        except Exception as e:
            print(f"Error al procesar el pago: {e}")
            QtWidgets.QMessageBox.critical(self.page_v3, "Error", f"Error al procesar el pago: {str(e)}")

    def update_difference(self, source_input, target_input):
        """Actualiza el campo de texto objetivo con la diferencia"""
        try:
            total = int(self.total_label.text().replace("Total: $", ""))
            source_text = source_input.text()
            
            if source_text:
                source_value = int(source_text)
                if source_value <= total:
                    difference = total - source_value
                    target_input.setText(str(difference))
                else:
                    target_input.setText("0")
            else:
                target_input.setText("0")
                
        except ValueError:
            target_input.setText("0")

    def retranslateUi(self, page_v3):
        _translate = QtCore.QCoreApplication.translate
        page_v3.setWindowTitle(_translate("page_v3", "page_v3"))
        self.user_active.setText(_translate("page_v3", "usuario activo: _____"))
        current_datetime = datetime.now().strftime("%d/%m/%Y %H:%M")
        self.datetime_label.setText(f"Fecha y hora: {current_datetime}")
        self.total_label.setText(_translate("page_v3", "Total: $0"))
        self.label.setText(_translate("page_v3", "Medio De Pago"))
        self.radioButton.setText(_translate("page_v3", "Efectivo"))
        self.radioButton_2.setText(_translate("page_v3", "Daviplata"))
        self.radioButton_3.setText(_translate("page_v3", "Pago Mixto"))
        self.radioButton_4.setText(_translate("page_v3", "Nequi"))
        self.pushButton_2.setText(_translate("page_v3", "Atrás"))
        self.pushButton.setText(_translate("page_v3", "OK"))
        self.recibido_label.setText(_translate("page_v3", "Recibido:"))
        self.radioButton_mixto_nequi.setText(_translate("page_v3", "Nequi"))
        self.radioButton_mixto_daviplata.setText(_translate("page_v3", "Daviplata"))
        self.efectivo_mixto_label.setText(_translate("page_v3", "Efectivo:"))
        self.transferencia_mixto_label.setText(_translate("page_v3", "Transferencia:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    page_v3 = QtWidgets.QDialog()
    ui = Ui_page_v3()
    ui.setupUi(page_v3)
    page_v3.show()
    sys.exit(app.exec_())
