# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_vfinal.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import datetime


class Ui_page_vfinal(object):
    def setupUi(self, page_vfinal):
        self.page_vfinal = page_vfinal  # Guardar referencia a la ventana principal
        self.parent_v2 = None  # Referencia a la ventana v2 padre
        page_vfinal.setObjectName("page_vfinal")
        page_vfinal.resize(1024, 600)
        page_vfinal.setWindowFlags(QtCore.Qt.Window | QtCore.Qt.CustomizeWindowHint | QtCore.Qt.WindowTitleHint)  # Disable close button
        page_vfinal.setWindowTitle("Pedido 1")  # Establecer título de la ventana principal

        # Establecer el color de fondo de la ventana (tono azul claro)
        page_vfinal.setStyleSheet("""
            QWidget {
                background-color: #E6F3FF;  /* Azul pastel claro */
            }
            QPushButton {
                background-color: #4A90E2;  /* Azul medio */
                border: 3px solid #2C5282;  /* Azul oscuro */
                border-radius: 15px;
                color: white;  /* Texto blanco para mejor contraste */
                font-weight: bold;
                padding: 5px;
            }
            QPushButton:hover {
                background-color: #2C5282;  /* Azul oscuro al pasar el mouse */
                color: white;
            }
            QLabel {
                color: #1A365D;  /* Azul muy oscuro para el texto */
                font-weight: bold;
            }
            QTableWidget {
                background-color: white;
                border: 3px solid #4A90E2;
                border-radius: 10px;
                gridline-color: #E6F3FF;
            }
            QTableWidget::item {
                padding: 5px;
            }
            QTableWidget::item:selected {
                background-color: #4A90E2;
                color: white;
            }
            QHeaderView::section {
                background-color: #4A90E2;
                color: white;
                padding: 5px;
                border: 1px solid #2C5282;
                font-weight: bold;
            }
            QLineEdit {
                background-color: white;
                border: 2px solid #4A90E2;
                border-radius: 10px;
                padding: 5px;
                color: #1A365D;
                font-weight: bold;
            }
            QLineEdit:focus {
                border: 2px solid #2C5282;
                background-color: #F0F7FF;
            }
            QRadioButton {
                color: #1A365D;
                font-weight: bold;
            }
            QRadioButton::indicator {
                width: 20px;
                height: 20px;
            }
            QRadioButton::indicator:unchecked {
                border: 2px solid #4A90E2;
                background-color: white;
                border-radius: 10px;
            }
            QRadioButton::indicator:checked {
                border: 2px solid #2C5282;
                background-color: #4A90E2;
                border-radius: 10px;
            }
        """)
        
        # Configurar fuente base
        base_font = QtGui.QFont()
        base_font.setPointSize(14)  # Tamaño de fuente base
        
        # Label para usuario activo
        self.user_active = QtWidgets.QLabel(page_vfinal)
        self.user_active.setGeometry(QtCore.QRect(50, 30, 400, 40))
        self.user_active.setObjectName("user_active")
        self.user_active.setFont(base_font)
        
        # Label para fecha y hora
        self.datetime_label = QtWidgets.QLabel(page_vfinal)
        self.datetime_label.setGeometry(QtCore.QRect(50, 80, 400, 40))
        self.datetime_label.setObjectName("datetime_label")
        self.datetime_label.setFont(base_font)
        
        # Label para el total
        self.total_label = QtWidgets.QLabel(page_vfinal)
        self.total_label.setGeometry(QtCore.QRect(50, 130, 400, 50))
        self.total_label.setObjectName("total_label")
        total_font = QtGui.QFont()
        total_font.setPointSize(20)  # Tamaño de fuente más grande para el total
        self.total_label.setFont(total_font)
        
        # Label para el cambio
        self.change_label = QtWidgets.QLabel(page_vfinal)
        self.change_label.setGeometry(QtCore.QRect(50, 190, 900, 100))  # Aumentado el alto a 100
        self.change_label.setObjectName("change_label")
        change_font = QtGui.QFont()
        change_font.setPointSize(28)  # Aumentado el tamaño de fuente a 28
        self.change_label.setFont(change_font)
        self.change_label.setWordWrap(True)
        self.change_label.setAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        
        # Label para método de pago
        self.payment_method_label = QtWidgets.QLabel(page_vfinal)
        self.payment_method_label.setGeometry(QtCore.QRect(50, 300, 900, 50))  # Ajustada la posición Y
        self.payment_method_label.setObjectName("payment_method_label")
        payment_font = QtGui.QFont()
        payment_font.setPointSize(16)
        self.payment_method_label.setFont(payment_font)
        self.payment_method_label.setWordWrap(True)
        self.payment_method_label.setAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        
        # Botón OK para cerrar la ventana
        self.ok_button = QtWidgets.QPushButton(page_vfinal)
        self.ok_button.setGeometry(QtCore.QRect(412, 500, 200, 60))  # Centrado y más grande
        self.ok_button.setObjectName("ok_button")
        self.ok_button.setFont(base_font)
        self.ok_button.clicked.connect(self.close_window)
        
        # Timer para actualizar la fecha y hora
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.update_datetime)
        self.timer.start(60000)  # Actualizar cada minuto (60000 ms)
        
        # Actualizar la fecha y hora inmediatamente
        current_datetime = datetime.now().strftime("%d/%m/%Y %H:%M")
        self.datetime_label.setText(f"Fecha y hora: {current_datetime}")
        
        self.retranslateUi(page_vfinal)
        QtCore.QMetaObject.connectSlotsByName(page_vfinal)

    def set_user_active(self, user_name):
        """Update the user_active label with the given username"""
        self.user_active.setText(f"usuario activo: {user_name}")

    def set_total(self, total, received=None):
        """Actualiza el label del total y calcula el cambio si se proporciona el monto recibido"""
        self.total_label.setText(f"Total: ${total}")
        
        if received is not None:
            try:
                # Convertir los valores a enteros
                total_value = int(total.replace('$', '').strip())
                received_value = int(received)
                
                # Calcular el cambio
                change = received_value - total_value
                
                # Mostrar el cambio o el desglose del pago mixto
                if change >= 0:
                    self.change_label.setText(f"Cambio: ${change}")
                else:
                    # En pago mixto, mostrar el desglose
                    transferencia = abs(change)
                    efectivo = total_value - transferencia
                    self.change_label.setText(f"Efectivo: ${efectivo} | Transferencia: ${transferencia}")
            except ValueError:
                self.change_label.setText("Cambio: Error en el cálculo")
        else:
            self.change_label.setText("Cambio: $0")

    def set_payment_method(self, payment_method):
        """Actualiza el label del método de pago"""
        self.payment_method_label.setText(f"Método de pago: {payment_method}")

    def update_datetime(self):
        """Actualiza la fecha y hora en el label"""
        try:
            current_datetime = datetime.now().strftime("%d/%m/%Y %H:%M")
            self.datetime_label.setText(f"Fecha y hora: {current_datetime}")
        except Exception as e:
            print(f"Error al actualizar la fecha y hora: {e}")
            self.datetime_label.setText("Fecha y hora: --/--/---- --:--")

    def set_parent_v2(self, parent_v2):
        """Guarda la referencia a la ventana v2 padre"""
        self.parent_v2 = parent_v2

    def close_window(self):
        """Vuelve a la ventana principal (Mesa 1) y cierra la actual"""
        try:
            # Importar aquí para evitar la importación circular
            from window.ventana_v2 import Ui_page_v2
            
            # Buscar la ventana principal (Mesa 1)
            if Ui_page_v2.main_window:
                # Solo limpiar la tabla y el total si estamos cerrando la ventana principal
                if self.parent_v2 == Ui_page_v2.main_window:
                    for window in QtWidgets.QApplication.topLevelWidgets():
                        if window == Ui_page_v2.main_window:
                            # Encontrar la instancia de Ui_page_v2 asociada
                            for child in window.children():
                                if isinstance(child, QtWidgets.QTableWidget):
                                    child.setRowCount(0)
                                elif isinstance(child, QtWidgets.QLabel) and child.objectName() == "label_2":
                                    child.setText("0")
                            break
                
                # Traer la ventana principal al frente
                Ui_page_v2.main_window.activateWindow()
                Ui_page_v2.main_window.raise_()
            
            # Cerrar la ventana v2 específica solo si no es la ventana principal
            if self.parent_v2 and self.parent_v2 != Ui_page_v2.main_window:
                self.parent_v2.close()
            
            # Cerrar la ventana actual
            self.page_vfinal.close()
            
        except Exception as e:
            print(f"Error al volver a la ventana principal: {e}")

    def retranslateUi(self, page_vfinal):
        _translate = QtCore.QCoreApplication.translate
        page_vfinal.setWindowTitle(_translate("page_vfinal", "page_vfinal"))
        self.user_active.setText(_translate("page_vfinal", "usuario activo: _____"))
        current_datetime = datetime.now().strftime("%d/%m/%Y %H:%M")
        self.datetime_label.setText(f"Fecha y hora: {current_datetime}")
        self.total_label.setText(_translate("page_vfinal", "Total: $0"))
        self.change_label.setText(_translate("page_vfinal", "Cambio: $0"))
        self.payment_method_label.setText(_translate("page_vfinal", "Método de pago: "))
        self.ok_button.setText(_translate("page_vfinal", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    page_vfinal = QtWidgets.QDialog()
    ui = Ui_page_vfinal()
    ui.setupUi(page_vfinal)
    page_vfinal.show()
    sys.exit(app.exec_())
